# Generated by Django 5.2.9 on 2025-12-07 19:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_add_recruiter_invitation'),
        ('scheduling', '0003_meetingtype_booking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(help_text='Email of the invitee', max_length=254)),
                ('name', models.CharField(blank=True, help_text='Name from booking form', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(blank=True, help_text='The booking that triggered this invitation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_invitations', to='scheduling.booking')),
                ('created_by', models.ForeignKey(help_text='Recruiter/admin who the meeting was booked with', on_delete=django.db.models.deletion.CASCADE, related_name='candidate_invitations_created', to=settings.AUTH_USER_MODEL)),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_invitation_used', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'candidate_invitations',
                'ordering': ['-created_at'],
            },
        ),
    ]
