# Generated by Django 5.2.9 on 2025-12-09 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_add_candidate_invitation_and_booking_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateinvitation',
            name='pending_user',
            field=models.ForeignKey(blank=True, help_text='The pending user created when booking was made (before signup completion)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_invitation_pending', to=settings.AUTH_USER_MODEL),
        ),
    ]
