# Generated by Django 5.2.9 on 2025-12-18 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_add_pending_user_to_candidate_invitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateinvitation',
            name='created_by',
            field=models.ForeignKey(help_text='Recruiter/admin who the meeting was booked with', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_invitations_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clientinvitation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_invitations_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recruiterinvitation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruiter_invitations_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
