# Generated by Django 5.2.9 on 2025-12-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_fix_cascade_deletions'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinvitation',
            name='offered_csuite_placement_fee',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Custom C-Suite placement fee as decimal (e.g., 0.15 = 15%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='clientinvitation',
            name='offered_monthly_retainer',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custom monthly retainer for the contract offer', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='clientinvitation',
            name='offered_placement_fee',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Custom placement fee as decimal (e.g., 0.10 = 10%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='clientinvitation',
            name='offered_service_type',
            field=models.CharField(blank=True, choices=[('headhunting', 'Headhunting'), ('retained', 'Retained')], help_text='Pre-configured service type for the contract offer', max_length=20, null=True),
        ),
    ]
