# Generated by Django 5.2.9 on 2025-12-24 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_client_onboarding'),
        ('companies', '0014_client_onboarding'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinvitation',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Link to existing company (lead) - when set, user joins this company on signup', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_invitations', to='companies.company'),
        ),
    ]
