# Generated by Django 5.2.9 on 2025-12-24 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_add_company_to_client_invitation'),
        ('companies', '0015_add_lead_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientinvitation',
            name='company',
        ),
        migrations.AddField(
            model_name='clientinvitation',
            name='lead',
            field=models.ForeignKey(blank=True, help_text='Link to prospecting lead - updates lead stage when invitation is created/used', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to='companies.lead'),
        ),
    ]
