# Generated by Django 5.2.9 on 2025-12-05 06:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandingSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(default='Oneo', help_text='Company/platform name', max_length=100)),
                ('tagline', models.CharField(blank=True, default='Recruitment Made Simple', help_text='Company tagline or slogan', max_length=200)),
                ('logo_url', models.URLField(blank=True, help_text='URL to main logo (recommended: PNG with transparent background)')),
                ('logo_dark_url', models.URLField(blank=True, help_text='URL to logo for dark backgrounds')),
                ('favicon_url', models.URLField(blank=True, help_text='URL to favicon')),
                ('primary_color', models.CharField(default='#111111', help_text='Primary brand color (hex)', max_length=7)),
                ('secondary_color', models.CharField(default='#0066cc', help_text='Secondary/accent color (hex)', max_length=7)),
                ('success_color', models.CharField(default='#10b981', help_text='Success state color (hex)', max_length=7)),
                ('warning_color', models.CharField(default='#f97316', help_text='Warning state color (hex)', max_length=7)),
                ('error_color', models.CharField(default='#ef4444', help_text='Error state color (hex)', max_length=7)),
                ('email_background_color', models.CharField(default='#f5f5f5', help_text='Email background color (hex)', max_length=7)),
                ('email_header_background', models.CharField(default='#fafafa', help_text='Email header background color (hex)', max_length=7)),
                ('email_footer_text', models.TextField(blank=True, default='If you have any questions, please contact the hiring team directly.', help_text='Custom footer text for emails')),
                ('website_url', models.URLField(blank=True, help_text='Company website URL')),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('support_email', models.EmailField(blank=True, help_text='Support email address', max_length=254)),
                ('contact_phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20)),
                ('address', models.TextField(blank=True, help_text='Company address')),
                ('privacy_policy_url', models.URLField(blank=True, help_text='Link to privacy policy')),
                ('terms_of_service_url', models.URLField(blank=True, help_text='Link to terms of service')),
                ('custom_css', models.TextField(blank=True, help_text='Custom CSS for emails (advanced)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_branding_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Branding Settings',
                'verbose_name_plural': 'Branding Settings',
                'db_table': 'branding_settings',
            },
        ),
    ]
