# Generated by Django 5.2.9 on 2025-12-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandingsettings',
            name='email_base_template',
            field=models.TextField(blank=True, help_text='Base HTML template for emails. Use Django template syntax with {{ branding.* }} variables.'),
        ),
    ]
