# Generated by Django 5.2.9 on 2025-12-05 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0002_add_email_base_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandingsettings',
            name='accent_color',
            field=models.CharField(default='#FF7B55', help_text='Accent/highlight color (hex)', max_length=7),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='accent_color_dark',
            field=models.CharField(default='#E65A35', help_text='Accent color - dark variant (hex)', max_length=7),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='accent_color_light',
            field=models.CharField(default='#FFAB97', help_text='Accent color - light variant (hex)', max_length=7),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='font_family',
            field=models.CharField(default='Poppins', help_text='Primary font family name (e.g., Poppins, Inter, Roboto)', max_length=200),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='primary_color_dark',
            field=models.CharField(default='#002A32', help_text='Primary color - dark variant (hex)', max_length=7),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='primary_color_light',
            field=models.CharField(default='#0D646D', help_text='Primary color - light variant (hex)', max_length=7),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='secondary_color_dark',
            field=models.CharField(default='#064852', help_text='Secondary color - dark variant (hex)', max_length=7),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='secondary_color_light',
            field=models.CharField(default='#1A7A88', help_text='Secondary color - light variant (hex)', max_length=7),
        ),
        migrations.AlterField(
            model_name='brandingsettings',
            name='primary_color',
            field=models.CharField(default='#003E49', help_text='Primary brand color (hex)', max_length=7),
        ),
        migrations.AlterField(
            model_name='brandingsettings',
            name='secondary_color',
            field=models.CharField(default='#0D646D', help_text='Secondary brand color (hex)', max_length=7),
        ),
    ]
