# Generated by Django 5.2.9 on 2025-12-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0003_add_color_variants_and_font'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandingsettings',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Upload favicon (recommended: .ico or .png, 32x32 or 16x16)', null=True, upload_to='branding/'),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload main logo (recommended: PNG with transparent background)', null=True, upload_to='branding/'),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='logo_dark',
            field=models.ImageField(blank=True, help_text='Upload logo for dark backgrounds', null=True, upload_to='branding/'),
        ),
        migrations.AlterField(
            model_name='brandingsettings',
            name='favicon_url',
            field=models.URLField(blank=True, help_text='URL to favicon (used if no file uploaded)'),
        ),
        migrations.AlterField(
            model_name='brandingsettings',
            name='logo_dark_url',
            field=models.URLField(blank=True, help_text='URL to logo for dark backgrounds (used if no file uploaded)'),
        ),
        migrations.AlterField(
            model_name='brandingsettings',
            name='logo_url',
            field=models.URLField(blank=True, help_text='URL to main logo (used if no file uploaded)'),
        ),
    ]
