# Generated by Django
from django.db import migrations


DEFAULT_EMAIL_TEMPLATE = '''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{{ branding.company_name|default:"Oneo" }}</title>
    <!--[if mso]>
    <noscript>
        <xml>
            <o:OfficeDocumentSettings>
                <o:PixelsPerInch>96</o:PixelsPerInch>
            </o:OfficeDocumentSettings>
        </xml>
    </noscript>
    <![endif]-->
    <style type="text/css">
        /* Reset styles */
        body, table, td, a { -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; }
        table, td { mso-table-lspace: 0pt; mso-table-rspace: 0pt; }
        img { -ms-interpolation-mode: bicubic; border: 0; height: auto; line-height: 100%; outline: none; text-decoration: none; }

        /* Base styles */
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
            line-height: 1.6;
            color: #333333;
            margin: 0;
            padding: 0;
            background-color: {{ branding.background_color|default:"#f5f5f5" }};
            width: 100% !important;
            height: 100% !important;
        }
        .email-wrapper {
            width: 100%;
            background-color: {{ branding.background_color|default:"#f5f5f5" }};
            padding: 40px 20px;
        }
        .email-container {
            max-width: 600px;
            margin: 0 auto;
            background-color: #ffffff;
            border-radius: 8px;
            box-shadow: 0 2px 8px rgba(0, 0, 0, 0.08);
            overflow: hidden;
        }
        .header {
            text-align: center;
            padding: 32px 32px 24px 32px;
            border-bottom: 1px solid #eaeaea;
            background-color: {{ branding.header_background|default:"#fafafa" }};
        }
        .logo {
            font-size: 28px;
            font-weight: 700;
            color: {{ branding.primary_color|default:"#111111" }};
            letter-spacing: -0.5px;
        }
        .logo a {
            color: {{ branding.primary_color|default:"#111111" }};
            text-decoration: none;
        }
        .logo img {
            max-height: 50px;
            width: auto;
        }
        .tagline {
            font-size: 13px;
            color: #666666;
            margin-top: 4px;
        }
        .content {
            padding: 32px;
        }
        h1 {
            color: {{ branding.primary_color|default:"#111111" }};
            font-size: 22px;
            font-weight: 600;
            margin: 0 0 20px 0;
            line-height: 1.3;
        }
        h2 {
            color: #333333;
            font-size: 16px;
            font-weight: 600;
            margin: 28px 0 12px 0;
        }
        p {
            margin: 0 0 16px 0;
            color: #555555;
            font-size: 15px;
        }
        a {
            color: {{ branding.secondary_color|default:"#0066cc" }};
        }
        .button {
            display: inline-block;
            padding: 14px 28px;
            background-color: {{ branding.primary_color|default:"#111111" }};
            color: #ffffff !important;
            text-decoration: none;
            border-radius: 6px;
            font-weight: 500;
            font-size: 15px;
            margin: 8px 0;
            transition: background-color 0.2s;
        }
        .button:hover {
            opacity: 0.9;
        }
        .button-secondary {
            background-color: #ffffff;
            color: {{ branding.primary_color|default:"#111111" }} !important;
            border: 2px solid {{ branding.primary_color|default:"#111111" }};
        }
        .button-success {
            background-color: {{ branding.success_color|default:"#10b981" }};
        }
        .details {
            background-color: #f9fafb;
            border-radius: 8px;
            padding: 20px;
            margin: 20px 0;
        }
        .details-row {
            display: flex;
            margin-bottom: 12px;
            font-size: 14px;
        }
        .details-row:last-child {
            margin-bottom: 0;
        }
        .details-label {
            font-weight: 600;
            color: #666666;
            width: 130px;
            flex-shrink: 0;
        }
        .details-value {
            color: #333333;
        }
        .highlight {
            background-color: #eff6ff;
            border-left: 4px solid {{ branding.secondary_color|default:"#3b82f6" }};
            padding: 16px 20px;
            margin: 20px 0;
            border-radius: 0 6px 6px 0;
        }
        .highlight p {
            margin: 0;
            color: #1e40af;
        }
        .warning {
            background-color: #fff7ed;
            border-left: 4px solid {{ branding.warning_color|default:"#f97316" }};
            padding: 16px 20px;
            margin: 20px 0;
            border-radius: 0 6px 6px 0;
        }
        .warning p {
            margin: 0;
            color: #9a3412;
        }
        .success {
            background-color: #ecfdf5;
            border-left: 4px solid {{ branding.success_color|default:"#10b981" }};
            padding: 16px 20px;
            margin: 20px 0;
            border-radius: 0 6px 6px 0;
        }
        .success p {
            margin: 0;
            color: #065f46;
        }
        .error {
            background-color: #fef2f2;
            border-left: 4px solid {{ branding.error_color|default:"#ef4444" }};
            padding: 16px 20px;
            margin: 20px 0;
            border-radius: 0 6px 6px 0;
        }
        .error p {
            margin: 0;
            color: #991b1b;
        }
        .divider {
            height: 1px;
            background-color: #eaeaea;
            margin: 24px 0;
        }
        .footer {
            padding: 24px 32px;
            background-color: {{ branding.header_background|default:"#fafafa" }};
            border-top: 1px solid #eaeaea;
            text-align: center;
        }
        .footer p {
            margin: 0 0 8px 0;
            color: #888888;
            font-size: 13px;
        }
        .footer p:last-child {
            margin-bottom: 0;
        }
        .footer a {
            color: #666666;
            text-decoration: none;
        }
        .footer a:hover {
            text-decoration: underline;
        }
        .footer-links {
            margin-top: 12px;
        }
        .footer-links a {
            margin: 0 8px;
        }
        .social-links {
            margin: 16px 0;
        }
        .social-links a {
            display: inline-block;
            margin: 0 8px;
            color: #666666;
        }
        .preheader {
            display: none !important;
            visibility: hidden;
            opacity: 0;
            color: transparent;
            height: 0;
            width: 0;
            max-height: 0;
            max-width: 0;
            overflow: hidden;
            mso-hide: all;
        }

        /* Custom CSS from branding settings */
        {{ branding.custom_css|default:""|safe }}

        /* Responsive styles */
        @media only screen and (max-width: 620px) {
            .email-wrapper {
                padding: 20px 10px;
            }
            .email-container {
                border-radius: 0;
            }
            .content {
                padding: 24px 20px;
            }
            .header {
                padding: 24px 20px 20px 20px;
            }
            .footer {
                padding: 20px;
            }
            h1 {
                font-size: 20px;
            }
            .details-row {
                flex-direction: column;
            }
            .details-label {
                width: 100%;
                margin-bottom: 4px;
            }
        }
    </style>
</head>
<body>
    <div class="email-wrapper">
        <div class="email-container">
            <!-- Header -->
            <div class="header">
                <div class="logo">
                    {% if branding.logo_url %}
                        <a href="{{ site_url }}"><img src="{{ branding.logo_url }}" alt="{{ branding.company_name|default:'Oneo' }}"></a>
                    {% else %}
                        <a href="{{ site_url }}">{{ branding.company_name|default:"Oneo" }}</a>
                    {% endif %}
                </div>
                {% if branding.tagline %}
                <div class="tagline">{{ branding.tagline }}</div>
                {% endif %}
            </div>

            <!-- Content -->
            <div class="content">
                {{ email_content|safe }}
            </div>

            <!-- Footer -->
            <div class="footer">
                <p>This email was sent by {{ branding.company_name|default:"Oneo" }}.</p>
                {% if branding.footer_text %}
                <p>{{ branding.footer_text }}</p>
                {% endif %}

                {% if branding.facebook_url or branding.twitter_url or branding.linkedin_url or branding.instagram_url %}
                <div class="social-links">
                    {% if branding.facebook_url %}<a href="{{ branding.facebook_url }}">Facebook</a>{% endif %}
                    {% if branding.twitter_url %}<a href="{{ branding.twitter_url }}">Twitter</a>{% endif %}
                    {% if branding.linkedin_url %}<a href="{{ branding.linkedin_url }}">LinkedIn</a>{% endif %}
                    {% if branding.instagram_url %}<a href="{{ branding.instagram_url }}">Instagram</a>{% endif %}
                </div>
                {% endif %}

                <div class="footer-links">
                    {% if branding.website_url %}
                    <a href="{{ branding.website_url }}">Visit {{ branding.company_name|default:"Oneo" }}</a> |
                    {% else %}
                    <a href="{{ site_url }}">Visit {{ branding.company_name|default:"Oneo" }}</a> |
                    {% endif %}
                    <a href="{{ site_url }}/settings/notifications">Email Preferences</a>
                    {% if branding.privacy_policy_url %}
                    | <a href="{{ branding.privacy_policy_url }}">Privacy Policy</a>
                    {% endif %}
                </div>
                <p style="margin-top: 16px; font-size: 12px; color: #aaa;">
                    &copy; {% now "Y" %} {{ branding.company_name|default:"Oneo" }}. All rights reserved.
                </p>
            </div>
        </div>
    </div>
</body>
</html>'''


def populate_email_template(apps, schema_editor):
    """Populate empty email_base_template fields with the default template."""
    BrandingSettings = apps.get_model('branding', 'BrandingSettings')
    BrandingSettings.objects.filter(email_base_template='').update(
        email_base_template=DEFAULT_EMAIL_TEMPLATE
    )


def reverse_populate(apps, schema_editor):
    """Reverse migration - no action needed."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0004_add_logo_image_fields'),
    ]

    operations = [
        migrations.RunPython(populate_email_template, reverse_populate),
    ]
