# Generated by Django 5.2.9 on 2025-12-02 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Industries',
                'db_table': 'industries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('category', models.CharField(choices=[('programming', 'Programming Languages'), ('framework', 'Frameworks & Libraries'), ('database', 'Databases'), ('devops', 'DevOps & Cloud'), ('design', 'Design'), ('soft_skill', 'Soft Skills'), ('other', 'Other')], default='other', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'skills',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('professional_title', models.CharField(blank=True, max_length=200)),
                ('headline', models.CharField(blank=True, max_length=300)),
                ('seniority', models.CharField(blank=True, choices=[('intern', 'Intern'), ('junior', 'Junior'), ('mid', 'Mid-Level'), ('senior', 'Senior'), ('lead', 'Lead'), ('principal', 'Principal'), ('executive', 'Executive')], max_length=20)),
                ('professional_summary', models.TextField(blank=True)),
                ('years_of_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('work_preference', models.CharField(blank=True, choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'On-site'), ('flexible', 'Flexible')], max_length=20)),
                ('willing_to_relocate', models.BooleanField(default=False)),
                ('preferred_locations', models.JSONField(blank=True, default=list)),
                ('salary_expectation_min', models.PositiveIntegerField(blank=True, null=True)),
                ('salary_expectation_max', models.PositiveIntegerField(blank=True, null=True)),
                ('salary_currency', models.CharField(choices=[('ZAR', 'South African Rand'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound')], default='ZAR', max_length=3)),
                ('notice_period_days', models.PositiveIntegerField(blank=True, null=True)),
                ('portfolio_links', models.JSONField(blank=True, default=list)),
                ('resume_url', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('public_sanitised', 'Public (Sanitised)')], default='public_sanitised', max_length=20)),
                ('profile_completeness', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL)),
                ('industries', models.ManyToManyField(blank=True, related_name='candidates', to='candidates.industry')),
                ('skills', models.ManyToManyField(blank=True, related_name='candidates', to='candidates.skill')),
            ],
            options={
                'verbose_name': 'Candidate Profile',
                'verbose_name_plural': 'Candidate Profiles',
                'db_table': 'candidate_profiles',
            },
        ),
    ]
