# Generated by Django 5.2.9 on 2025-12-02 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_education_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('category', models.CharField(choices=[('language', 'Programming Languages'), ('framework', 'Frameworks & Libraries'), ('database', 'Databases'), ('cloud', 'Cloud & Infrastructure'), ('devops', 'DevOps & CI/CD'), ('tool', 'Development Tools'), ('other', 'Other')], default='other', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Technologies',
                'db_table': 'technologies',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='experience',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='experiences', to='candidates.skill'),
        ),
        migrations.AddField(
            model_name='experience',
            name='technologies',
            field=models.ManyToManyField(blank=True, related_name='experiences', to='candidates.technology'),
        ),
    ]
