# Generated by Django 5.2.9 on 2025-12-02 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_technology_experience_skills_experience_technologies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('leadership', 'Leadership & Management'), ('communication', 'Communication'), ('project_management', 'Project Management'), ('analytical', 'Analytical & Problem Solving'), ('interpersonal', 'Interpersonal'), ('business', 'Business & Strategy'), ('domain', 'Domain Expertise'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
