# Generated by Django 5.2.9 on 2025-12-03 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_update_skill_categories'),
        ('companies', '0005_add_company_invitation_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='city_rel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='companies.city'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='country_rel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='companies.country'),
        ),
    ]
