# Generated by Django 5.2.9 on 2025-12-06 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_add_location_foreignkeys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='skills',
        ),
    ]
