# Generated by Django 5.2.9 on 2025-12-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0006_remove_skills_from_candidate_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='needs_review',
            field=models.BooleanField(default=False, help_text='True if auto-imported from resume and needs admin review'),
        ),
        migrations.AddField(
            model_name='technology',
            name='needs_review',
            field=models.BooleanField(default=False, help_text='True if auto-imported from resume and needs admin review'),
        ),
    ]
