# Generated by Django 5.2.9 on 2025-12-06 18:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0007_add_needs_review_field'),
        ('jobs', '0013_add_offer_declined_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('profile_updated', 'Profile Updated'), ('job_viewed', 'Job Viewed'), ('logged_in', 'Logged In'), ('resume_uploaded', 'Resume Uploaded'), ('resume_parsed', 'Resume Parsed'), ('experience_added', 'Experience Added'), ('experience_updated', 'Experience Updated'), ('education_added', 'Education Added'), ('education_updated', 'Education Updated')], max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='candidates.candidateprofile')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_views', to='jobs.job')),
                ('performed_by', models.ForeignKey(blank=True, help_text='User who performed this action (may differ from candidate for admin actions)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_activities_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Candidate Activity',
                'verbose_name_plural': 'Candidate Activities',
                'db_table': 'candidate_activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateActivityNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='candidates.candidateactivity')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_activity_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'candidate_activity_notes',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='candidateactivity',
            index=models.Index(fields=['candidate', '-created_at'], name='candidate_a_candida_13af6b_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateactivity',
            index=models.Index(fields=['activity_type', '-created_at'], name='candidate_a_activit_4d7dd5_idx'),
        ),
    ]
