# Generated by Django 5.2.9 on 2025-12-06 21:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0008_add_candidate_activity_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateactivity',
            name='activity_type',
            field=models.CharField(choices=[('profile_updated', 'Profile Updated'), ('profile_viewed', 'Profile Viewed'), ('job_viewed', 'Job Viewed'), ('logged_in', 'Logged In'), ('resume_uploaded', 'Resume Uploaded'), ('resume_parsed', 'Resume Parsed'), ('experience_added', 'Experience Added'), ('experience_updated', 'Experience Updated'), ('education_added', 'Education Added'), ('education_updated', 'Education Updated')], max_length=30),
        ),
        migrations.CreateModel(
            name='ProfileSuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_type', models.CharField(choices=[('profile', 'Profile'), ('experience', 'Experience'), ('education', 'Education')], help_text='Type of field: profile, experience, or education', max_length=20)),
                ('field_name', models.CharField(help_text='Field name like headline, description, job_title', max_length=100)),
                ('related_object_id', models.UUIDField(blank=True, help_text='UUID of Experience or Education entry (null for profile fields)', null=True)),
                ('suggestion_text', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('declined', 'Declined'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True, help_text='Reason for decline or notes on resolution')),
                ('reopened_at', models.DateTimeField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_suggestions', to='candidates.candidateprofile')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_profile_suggestions', to=settings.AUTH_USER_MODEL)),
                ('reopened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reopened_profile_suggestions', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_profile_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile_suggestions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['candidate', 'status'], name='profile_sug_candida_573ba2_idx'), models.Index(fields=['field_type', 'related_object_id'], name='profile_sug_field_t_d4b289_idx')],
            },
        ),
    ]
