# Generated by Django 5.2.9 on 2025-12-08 16:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0010_add_assigned_to_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, help_text='Assigned recruiters or admins as dedicated contact points', related_name='assigned_candidates', to=settings.AUTH_USER_MODEL),
        ),
    ]
