# Generated by Django 5.2.9 on 2025-12-27 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('notifications', '0011_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automationrule',
            name='action_node_id',
        ),
        migrations.RemoveField(
            model_name='automationrule',
            name='trigger_node_id',
        ),
        migrations.AddField(
            model_name='automationrule',
            name='notification_template',
            field=models.ForeignKey(blank=True, help_text='Use existing notification template instead of inline config', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_rules', to='notifications.notificationtemplate'),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='action_config',
            field=models.JSONField(default=dict, help_text='Action settings. For webhook: {"url", "method", "headers", "payload_template"}. For notification: {"channel", "recipient_type", "title_template", "body_template"}'),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='action_type',
            field=models.CharField(choices=[('send_webhook', 'Send Webhook'), ('send_notification', 'Send Notification'), ('create_activity', 'Log Activity'), ('update_field', 'Update Field')], max_length=30),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='trigger_conditions',
            field=models.JSONField(default=list, help_text='Array of conditions: [{"field": "status", "operator": "equals", "value": "active"}]'),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='trigger_content_type',
            field=models.ForeignKey(help_text='The model that triggers this automation', on_delete=django.db.models.deletion.CASCADE, related_name='automation_triggers', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='workflow',
            field=models.ForeignKey(blank=True, help_text='Parent workflow this rule belongs to (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to='automations.workflow'),
        ),
    ]
