# Generated by Django 5.2.9 on 2025-12-28 07:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0002_remove_automationrule_action_node_id_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_type', models.CharField(max_length=30)),
                ('trigger_object_id', models.CharField(blank=True, max_length=50)),
                ('trigger_data', models.JSONField(default=dict, help_text='Snapshot of old_values and new_values at execution time')),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped (conditions not met)')], default='running', max_length=20)),
                ('action_type', models.CharField(blank=True, max_length=30)),
                ('action_result', models.JSONField(default=dict, help_text='Result returned by the action executor')),
                ('error_message', models.TextField(blank=True)),
                ('is_test', models.BooleanField(default=False, help_text='Whether this was a test execution')),
                ('execution_time_ms', models.IntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='automations.automationrule')),
                ('trigger_content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('triggered_by', models.ForeignKey(blank=True, help_text='User who triggered this (for manual/test executions)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rule Execution',
                'verbose_name_plural': 'Rule Executions',
                'db_table': 'rule_executions',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['rule', '-started_at'], name='rule_execut_rule_id_8d1a51_idx'), models.Index(fields=['status', '-started_at'], name='rule_execut_status_16d9ac_idx')],
            },
        ),
    ]
