# Generated by Django 5.2.9 on 2025-12-28 11:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0003_add_rule_execution'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationrule',
            name='schedule_config',
            field=models.JSONField(blank=True, help_text='Config for scheduled triggers: {"datetime_field": "scheduled_at", "offset_hours": -24, "offset_type": "before"}', null=True),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='trigger_type',
            field=models.CharField(choices=[('model_created', 'Record Created'), ('model_updated', 'Record Updated'), ('model_deleted', 'Record Deleted'), ('stage_changed', 'Stage Changed'), ('status_changed', 'Status Changed'), ('field_changed', 'Field Changed'), ('scheduled', 'Scheduled (Time-based)')], max_length=30),
        ),
        migrations.CreateModel(
            name='ScheduledTriggerExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.CharField(max_length=50)),
                ('trigger_datetime', models.DateTimeField(help_text='The datetime field value that triggered this execution')),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_trigger', to='automations.ruleexecution')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_executions', to='automations.automationrule')),
            ],
            options={
                'verbose_name': 'Scheduled Trigger Execution',
                'verbose_name_plural': 'Scheduled Trigger Executions',
                'db_table': 'scheduled_trigger_executions',
                'ordering': ['-executed_at'],
                'indexes': [models.Index(fields=['rule', 'content_type', 'object_id'], name='scheduled_t_rule_id_424d7b_idx')],
                'unique_together': {('rule', 'content_type', 'object_id', 'trigger_datetime')},
            },
        ),
    ]
