# Generated by Django 5.2.9 on 2025-12-28 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0004_add_scheduled_triggers'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationrule',
            name='signal_name',
            field=models.CharField(blank=True, help_text='Signal name (e.g., "password_reset", "email_verification") or view action name (e.g., "booking_link_sent")', max_length=100),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='trigger_content_type',
            field=models.ForeignKey(blank=True, help_text='The model that triggers this automation (optional for signal/manual triggers)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automation_triggers', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='trigger_type',
            field=models.CharField(choices=[('model_created', 'Record Created'), ('model_updated', 'Record Updated'), ('model_deleted', 'Record Deleted'), ('stage_changed', 'Stage Changed'), ('status_changed', 'Status Changed'), ('field_changed', 'Field Changed'), ('scheduled', 'Scheduled (Time-based)'), ('manual', 'Manual Trigger'), ('signal', 'Django Signal'), ('view_action', 'View Action')], max_length=30),
        ),
    ]
