# Generated by Django 5.2.9 on 2025-12-04 22:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0011_remove_notification_application_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('stage_scheduled', 'Interview Scheduled'), ('stage_reminder', 'Interview Reminder'), ('stage_rescheduled', 'Interview Rescheduled'), ('stage_cancelled', 'Interview Cancelled'), ('assessment_assigned', 'Assessment Assigned'), ('assessment_reminder', 'Assessment Deadline Reminder'), ('submission_received', 'Submission Received'), ('application_received', 'Application Received'), ('application_shortlisted', 'Application Shortlisted'), ('application_rejected', 'Application Rejected'), ('offer_received', 'Offer Received')], max_length=30)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('in_app', 'In-App'), ('both', 'Email & In-App')], default='both', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('action_url', models.URLField(blank=True, help_text='URL to navigate to when notification is clicked')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_error', models.TextField(blank=True, help_text='Error message if email sending failed')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='jobs.application')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('stage_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='jobs.applicationstageinstance')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['recipient', '-sent_at'], name='notificatio_recipie_d64ba4_idx'), models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_583549_idx')],
            },
        ),
    ]
