# Generated by Django 5.2.9 on 2025-12-05 05:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('stage_scheduled', 'Interview Scheduled'), ('stage_reminder', 'Interview Reminder'), ('stage_rescheduled', 'Interview Rescheduled'), ('stage_cancelled', 'Interview Cancelled'), ('assessment_assigned', 'Assessment Assigned'), ('assessment_reminder', 'Assessment Deadline Reminder'), ('submission_received', 'Submission Received'), ('application_received', 'Application Received'), ('application_shortlisted', 'Application Shortlisted'), ('application_rejected', 'Application Rejected'), ('offer_received', 'Offer Received'), ('admin_broadcast', 'Admin Broadcast'), ('custom', 'Custom Notification')], max_length=30),
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Unique name for this template', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of when/how this template is used')),
                ('template_type', models.CharField(blank=True, choices=[('stage_scheduled', 'Interview Scheduled'), ('stage_reminder', 'Interview Reminder'), ('stage_rescheduled', 'Interview Rescheduled'), ('stage_cancelled', 'Interview Cancelled'), ('assessment_assigned', 'Assessment Assigned'), ('assessment_reminder', 'Assessment Deadline Reminder'), ('submission_received', 'Submission Received'), ('application_received', 'Application Received'), ('application_shortlisted', 'Application Shortlisted'), ('application_rejected', 'Application Rejected'), ('offer_received', 'Offer Received'), ('admin_broadcast', 'Admin Broadcast'), ('custom', 'Custom Notification')], help_text='System notification type this template is for (leave blank for custom)', max_length=30)),
                ('is_custom', models.BooleanField(default=False, help_text='True for user-created templates')),
                ('title_template', models.CharField(help_text='Title template with {variables}', max_length=200)),
                ('body_template', models.TextField(help_text='Body template with {variables}')),
                ('email_subject_template', models.CharField(blank=True, help_text='Email subject template (defaults to title if blank)', max_length=200)),
                ('email_body_template', models.TextField(blank=True, help_text='HTML email body template (defaults to body if blank)')),
                ('default_channel', models.CharField(choices=[('email', 'Email'), ('in_app', 'In-App'), ('both', 'Email & In-App')], default='both', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive templates cannot be used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notification_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_templates',
                'ordering': ['name'],
            },
        ),
    ]
