# Generated by Django - Seed notification templates

from django.db import migrations


def seed_templates(apps, schema_editor):
    """Create default notification templates for all notification types."""
    NotificationTemplate = apps.get_model('notifications', 'NotificationTemplate')

    templates = [
        # =================================================================
        # Interview/Stage Notifications (Candidate)
        # =================================================================
        {
            'name': 'Interview Scheduled (Candidate)',
            'description': 'Sent to candidate when an interview is scheduled',
            'template_type': 'stage_scheduled',
            'is_custom': False,
            'title_template': 'Interview Scheduled: {stage_name}',
            'body_template': 'Your {stage_name} for {job_title} at {company_name} has been scheduled for {scheduled_time}.',
            'email_subject_template': 'Interview Scheduled - {company_name}',
            'email_body_template': '''
<html>
<body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
    <div style="max-width: 600px; margin: 0 auto; padding: 20px;">
        <h2 style="color: #1a1a1a; margin-bottom: 20px;">Interview Scheduled</h2>

        <p>Hi {first_name},</p>

        <p>Great news! Your <strong>{stage_name}</strong> for the <strong>{job_title}</strong> position at <strong>{company_name}</strong> has been scheduled.</p>

        <div style="background: #f5f5f5; padding: 20px; border-radius: 8px; margin: 20px 0;">
            <p style="margin: 0;"><strong>Date & Time:</strong> {scheduled_time}</p>
            <p style="margin: 10px 0 0;"><strong>Duration:</strong> {duration} minutes</p>
            {% if location %}
            <p style="margin: 10px 0 0;"><strong>Location:</strong> {location}</p>
            {% endif %}
            {% if meeting_link %}
            <p style="margin: 10px 0 0;"><strong>Meeting Link:</strong> <a href="{meeting_link}">{meeting_link}</a></p>
            {% endif %}
        </div>

        <p>Please make sure to:</p>
        <ul>
            <li>Be ready 5 minutes before the scheduled time</li>
            <li>Test your video/audio if it's a virtual interview</li>
            <li>Have a copy of your resume ready</li>
        </ul>

        <p>Good luck!</p>

        <p style="color: #666; font-size: 12px; margin-top: 30px;">
            - The {company_name} Team
        </p>
    </div>
</body>
</html>
''',
            'default_channel': 'both',
            'is_active': True,
        },
        {
            'name': 'Interview Scheduled (Interviewer)',
            'description': 'Sent to interviewer when an interview is scheduled',
            'template_type': 'stage_scheduled',
            'is_custom': False,
            'title_template': 'Interview Scheduled: {candidate_name}',
            'body_template': 'You have an interview scheduled with {candidate_name} for {job_title} on {scheduled_time}.',
            'email_subject_template': 'Interview Scheduled - {candidate_name}',
            'email_body_template': '''
<html>
<body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
    <div style="max-width: 600px; margin: 0 auto; padding: 20px;">
        <h2 style="color: #1a1a1a; margin-bottom: 20px;">Interview Scheduled</h2>

        <p>Hi,</p>

        <p>You have an upcoming interview with <strong>{candidate_name}</strong> for the <strong>{job_title}</strong> position.</p>

        <div style="background: #f5f5f5; padding: 20px; border-radius: 8px; margin: 20px 0;">
            <p style="margin: 0;"><strong>Candidate:</strong> {candidate_name}</p>
            <p style="margin: 10px 0 0;"><strong>Position:</strong> {job_title}</p>
            <p style="margin: 10px 0 0;"><strong>Date & Time:</strong> {scheduled_time}</p>
            <p style="margin: 10px 0 0;"><strong>Duration:</strong> {duration} minutes</p>
        </div>

        <p><a href="{action_url}" style="display: inline-block; background: #1a1a1a; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px;">View Application</a></p>
    </div>
</body>
</html>
''',
            'default_channel': 'both',
            'is_active': True,
        },
        {
            'name': 'Interview Reminder (Candidate)',
            'description': 'Sent to candidate as a reminder for upcoming interview',
            'template_type': 'stage_reminder',
            'is_custom': False,
            'title_template': 'Interview Tomorrow: {stage_name}',
            'body_template': 'Reminder: You have {stage_name} for {job_title} tomorrow at {time}.',
            'email_subject_template': 'Interview Reminder - Tomorrow at {time}',
            'email_body_template': '''
<html>
<body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
    <div style="max-width: 600px; margin: 0 auto; padding: 20px;">
        <h2 style="color: #1a1a1a; margin-bottom: 20px;">Interview Reminder</h2>

        <p>Hi {first_name},</p>

        <p>This is a friendly reminder that you have an interview <strong>tomorrow</strong>.</p>

        <div style="background: #fff3cd; padding: 20px; border-radius: 8px; margin: 20px 0; border-left: 4px solid #ffc107;">
            <p style="margin: 0;"><strong>{stage_name}</strong></p>
            <p style="margin: 10px 0 0;"><strong>Time:</strong> {time}</p>
            <p style="margin: 10px 0 0;"><strong>Position:</strong> {job_title} at {company_name}</p>
            {% if meeting_link %}
            <p style="margin: 10px 0 0;"><strong>Meeting Link:</strong> <a href="{meeting_link}">{meeting_link}</a></p>
            {% endif %}
        </div>

        <p>Good luck with your interview!</p>

        <p style="color: #666; font-size: 12px; margin-top: 30px;">
            - The {company_name} Team
        </p>
    </div>
</body>
</html>
''',
            'default_channel': 'both',
            'is_active': True,
        },
        {
            'name': 'Interview Rescheduled',
            'description': 'Sent when an interview is rescheduled',
            'template_type': 'stage_rescheduled',
            'is_custom': False,
            'title_template': 'Interview Rescheduled: {stage_name}',
            'body_template': 'Your {stage_name} for {job_title} has been rescheduled to {scheduled_time}.',
            'email_subject_template': 'Interview Rescheduled - {company_name}',
            'email_body_template': '''
<html>
<body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
    <div style="max-width: 600px; margin: 0 auto; padding: 20px;">
        <h2 style="color: #1a1a1a; margin-bottom: 20px;">Interview Rescheduled</h2>

        <p>Hi {first_name},</p>

        <p>Your <strong>{stage_name}</strong> for the <strong>{job_title}</strong> position has been rescheduled.</p>

        <div style="background: #f5f5f5; padding: 20px; border-radius: 8px; margin: 20px 0;">
            <p style="margin: 0;"><strong>New Date & Time:</strong> {scheduled_time}</p>
            {% if reason %}
            <p style="margin: 10px 0 0;"><strong>Reason:</strong> {reason}</p>
            {% endif %}
        </div>

        <p>Please update your calendar accordingly. We apologize for any inconvenience.</p>

        <p style="color: #666; font-size: 12px; margin-top: 30px;">
            - The {company_name} Team
        </p>
    </div>
</body>
</html>
''',
            'default_channel': 'both',
            'is_active': True,
        },
        {
            'name': 'Interview Cancelled',
            'description': 'Sent when an interview is cancelled',
            'template_type': 'stage_cancelled',
            'is_custom': False,
            'title_template': 'Interview Cancelled: {stage_name}',
            'body_template': 'Your {stage_name} for {job_title} has been cancelled.',
            'email_subject_template': 'Interview Cancelled - {company_name}',
            'email_body_template': '''
<html>
<body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
    <div style="max-width: 600px; margin: 0 auto; padding: 20px;">
        <h2 style="color: #1a1a1a; margin-bottom: 20px;">Interview Cancelled</h2>

        <p>Hi {first_name},</p>

        <p>We regret to inform you that your <strong>{stage_name}</strong> for the <strong>{job_title}</strong> position has been cancelled.</p>

        {% if reason %}
        <div style="background: #f5f5f5; padding: 20px; border-radius: 8px; margin: 20px 0;">
            <p style="margin: 0;"><strong>Reason:</strong> {reason}</p>
        </div>
        {% endif %}

        <p>If you have any questions, please don't hesitate to reach out.</p>

        <p style="color: #666; font-size: 12px; margin-top: 30px;">
            - The {company_name} Team
        </p>
    </div>
</body>
</html>
''',
            'default_channel': 'both',
            'is_active': True,
        },

        # =================================================================
        # Assessment Notifications
        # =================================================================
        {
            'name': 'Assessment Assigned',
            'description': 'Sent to candidate when an assessment is assigned',
            'template_type': 'assessment_assigned',
            'is_custom': False,
            'title_template': 'Assessment Assigned: {stage_name}',
            'body_template': 'You have been assigned a {stage_name} for {job_title}. Deadline: {deadline}',
            'email_subject_template': 'Assessment Assigned - {job_title}',
            'email_body_template': '''
<html>
<body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
    <div style="max-width: 600px; margin: 0 auto; padding: 20px;">
        <h2 style="color: #1a1a1a; margin-bottom: 20px;">Assessment Assigned</h2>

        <p>Hi {first_name},</p>

        <p>As part of your application for the <strong>{job_title}</strong> position at <strong>{company_name}</strong>, you have been assigned an assessment to complete.</p>

        <div style="background: #f5f5f5; padding: 20px; border-radius: 8px; margin: 20px 0;">
            <p style="margin: 0;"><strong>Assessment:</strong> {stage_name}</p>
            <p style="margin: 10px 0 0;"><strong>Deadline:</strong> {deadline}</p>
            {% if instructions %}
            <p style="margin: 10px 0 0;"><strong>Instructions:</strong> {instructions}</p>
            {% endif %}
        </div>

        {% if external_url %}
        <p><a href="{external_url}" style="display: inline-block; background: #1a1a1a; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px;">Start Assessment</a></p>
        {% endif %}

        <p>Please complete the assessment before the deadline. Good luck!</p>

        <p style="color: #666; font-size: 12px; margin-top: 30px;">
            - The {company_name} Team
        </p>
    </div>
</body>
</html>
''',
            'default_channel': 'both',
            'is_active': True,
        },
        {
            'name': 'Assessment Deadline Reminder',
            'description': 'Sent to candidate as a reminder for assessment deadline',
            'template_type': 'assessment_reminder',
            'is_custom': False,
            'title_template': 'Assessment Due Tomorrow: {stage_name}',
            'body_template': 'Reminder: Your {stage_name} for {job_title} is due tomorrow.',
            'email_subject_template': 'Assessment Due Tomorrow - {job_title}',
            'email_body_template': '''
<html>
<body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
    <div style="max-width: 600px; margin: 0 auto; padding: 20px;">
        <h2 style="color: #1a1a1a; margin-bottom: 20px;">Assessment Deadline Reminder</h2>

        <p>Hi {first_name},</p>

        <p>This is a friendly reminder that your assessment is due <strong>tomorrow</strong>.</p>

        <div style="background: #fff3cd; padding: 20px; border-radius: 8px; margin: 20px 0; border-left: 4px solid #ffc107;">
            <p style="margin: 0;"><strong>Assessment:</strong> {stage_name}</p>
            <p style="margin: 10px 0 0;"><strong>Position:</strong> {job_title}</p>
            <p style="margin: 10px 0 0;"><strong>Deadline:</strong> {deadline}</p>
        </div>

        <p>Please make sure to submit your assessment before the deadline.</p>

        <p style="color: #666; font-size: 12px; margin-top: 30px;">
            - The {company_name} Team
        </p>
    </div>
</body>
</html>
''',
            'default_channel': 'both',
            'is_active': True,
        },
        {
            'name': 'Assessment Submitted',
            'description': 'Sent to recruiter when candidate submits an assessment',
            'template_type': 'submission_received',
            'is_custom': False,
            'title_template': 'Assessment Submitted: {candidate_name}',
            'body_template': '{candidate_name} has submitted their {stage_name} for {job_title}.',
            'email_subject_template': 'Assessment Submitted - {candidate_name}',
            'email_body_template': '''
<html>
<body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
    <div style="max-width: 600px; margin: 0 auto; padding: 20px;">
        <h2 style="color: #1a1a1a; margin-bottom: 20px;">Assessment Submitted</h2>

        <p>Hi,</p>

        <p><strong>{candidate_name}</strong> has submitted their assessment.</p>

        <div style="background: #f5f5f5; padding: 20px; border-radius: 8px; margin: 20px 0;">
            <p style="margin: 0;"><strong>Candidate:</strong> {candidate_name}</p>
            <p style="margin: 10px 0 0;"><strong>Assessment:</strong> {stage_name}</p>
            <p style="margin: 10px 0 0;"><strong>Position:</strong> {job_title}</p>
        </div>

        <p><a href="{action_url}" style="display: inline-block; background: #1a1a1a; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px;">Review Submission</a></p>
    </div>
</body>
</html>
''',
            'default_channel': 'both',
            'is_active': True,
        },

        # =================================================================
        # Application Notifications
        # =================================================================
        {
            'name': 'Application Received',
            'description': 'Sent to recruiter when a new application is submitted',
            'template_type': 'application_received',
            'is_custom': False,
            'title_template': 'New Application: {candidate_name}',
            'body_template': '{candidate_name} has applied for {job_title}.',
            'email_subject_template': 'New Application - {job_title}',
            'email_body_template': '''
<html>
<body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
    <div style="max-width: 600px; margin: 0 auto; padding: 20px;">
        <h2 style="color: #1a1a1a; margin-bottom: 20px;">New Application Received</h2>

        <p>Hi,</p>

        <p>You have received a new application for the <strong>{job_title}</strong> position.</p>

        <div style="background: #f5f5f5; padding: 20px; border-radius: 8px; margin: 20px 0;">
            <p style="margin: 0;"><strong>Candidate:</strong> {candidate_name}</p>
            <p style="margin: 10px 0 0;"><strong>Position:</strong> {job_title}</p>
            <p style="margin: 10px 0 0;"><strong>Applied:</strong> {applied_at}</p>
        </div>

        <p><a href="{action_url}" style="display: inline-block; background: #1a1a1a; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px;">View Application</a></p>
    </div>
</body>
</html>
''',
            'default_channel': 'both',
            'is_active': True,
        },
        {
            'name': 'Application Shortlisted',
            'description': 'Sent to candidate when their application is shortlisted',
            'template_type': 'application_shortlisted',
            'is_custom': False,
            'title_template': 'Application Update: {job_title}',
            'body_template': 'Great news! Your application for {job_title} at {company_name} has been shortlisted.',
            'email_subject_template': 'Application Update - {company_name}',
            'email_body_template': '''
<html>
<body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
    <div style="max-width: 600px; margin: 0 auto; padding: 20px;">
        <h2 style="color: #1a1a1a; margin-bottom: 20px;">Application Shortlisted!</h2>

        <p>Hi {first_name},</p>

        <p>Great news! Your application for the <strong>{job_title}</strong> position at <strong>{company_name}</strong> has been <strong>shortlisted</strong>.</p>

        <div style="background: #d4edda; padding: 20px; border-radius: 8px; margin: 20px 0; border-left: 4px solid #28a745;">
            <p style="margin: 0; color: #155724;">You've made it to the next round! The hiring team was impressed with your profile and would like to move forward with your application.</p>
        </div>

        <p>We'll be in touch soon with next steps. In the meantime, please keep an eye on your email for updates.</p>

        <p><a href="{action_url}" style="display: inline-block; background: #1a1a1a; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px;">View Application</a></p>

        <p style="color: #666; font-size: 12px; margin-top: 30px;">
            - The {company_name} Team
        </p>
    </div>
</body>
</html>
''',
            'default_channel': 'both',
            'is_active': True,
        },
        {
            'name': 'Application Rejected',
            'description': 'Sent to candidate when their application is rejected',
            'template_type': 'application_rejected',
            'is_custom': False,
            'title_template': 'Application Update: {job_title}',
            'body_template': 'Thank you for your interest in {job_title} at {company_name}. Unfortunately, we will not be moving forward with your application at this time.',
            'email_subject_template': 'Application Update - {company_name}',
            'email_body_template': '''
<html>
<body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
    <div style="max-width: 600px; margin: 0 auto; padding: 20px;">
        <h2 style="color: #1a1a1a; margin-bottom: 20px;">Application Update</h2>

        <p>Hi {first_name},</p>

        <p>Thank you for your interest in the <strong>{job_title}</strong> position at <strong>{company_name}</strong> and for taking the time to apply.</p>

        <p>After careful consideration, we have decided not to move forward with your application at this time. This was a difficult decision as we received many qualified applicants.</p>

        <p>We encourage you to:</p>
        <ul>
            <li>Keep an eye on our careers page for future opportunities</li>
            <li>Continue to develop your skills and experience</li>
            <li>Feel free to apply for other positions that match your profile</li>
        </ul>

        <p>We wish you the best in your job search and future career endeavors.</p>

        <p style="color: #666; font-size: 12px; margin-top: 30px;">
            - The {company_name} Team
        </p>
    </div>
</body>
</html>
''',
            'default_channel': 'both',
            'is_active': True,
        },
        {
            'name': 'Offer Received',
            'description': 'Sent to candidate when they receive a job offer',
            'template_type': 'offer_received',
            'is_custom': False,
            'title_template': 'Job Offer: {job_title}',
            'body_template': 'Congratulations! You have received an offer for {job_title} at {company_name}.',
            'email_subject_template': 'Job Offer - {company_name}',
            'email_body_template': '''
<html>
<body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
    <div style="max-width: 600px; margin: 0 auto; padding: 20px;">
        <h2 style="color: #1a1a1a; margin-bottom: 20px;">Congratulations! You've Received an Offer</h2>

        <p>Hi {first_name},</p>

        <p>We are thrilled to inform you that you have been selected for the <strong>{job_title}</strong> position at <strong>{company_name}</strong>!</p>

        <div style="background: #d4edda; padding: 20px; border-radius: 8px; margin: 20px 0; border-left: 4px solid #28a745;">
            <p style="margin: 0; color: #155724; font-size: 18px;">We would like to offer you this position!</p>
        </div>

        <p>Your skills, experience, and interview performance impressed our team, and we believe you would be a great addition to {company_name}.</p>

        <p>Please review the offer details and let us know your decision. If you have any questions, don't hesitate to reach out.</p>

        <p><a href="{action_url}" style="display: inline-block; background: #28a745; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px;">View Offer Details</a></p>

        <p style="color: #666; font-size: 12px; margin-top: 30px;">
            - The {company_name} Team
        </p>
    </div>
</body>
</html>
''',
            'default_channel': 'both',
            'is_active': True,
        },

        # =================================================================
        # Self-Scheduling / Booking Notifications
        # =================================================================
        {
            'name': 'Self-Schedule Interview Link',
            'description': 'Sent to candidate with a link to self-schedule their interview',
            'template_type': 'stage_scheduled',
            'is_custom': True,
            'title_template': 'Schedule Your Interview: {stage_name}',
            'body_template': 'Please select a time for your {stage_name} for the {job_title} position at {company_name}.',
            'email_subject_template': 'Schedule Your Interview - {company_name}',
            'email_body_template': '''
<html>
<body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
    <div style="max-width: 600px; margin: 0 auto; padding: 20px;">
        <h2 style="color: #1a1a1a; margin-bottom: 20px;">Schedule Your Interview</h2>

        <p>Hi {first_name},</p>

        <p>You've been invited to schedule your <strong>{stage_name}</strong> for the <strong>{job_title}</strong> position at <strong>{company_name}</strong>.</p>

        <div style="background: #f5f5f5; padding: 20px; border-radius: 8px; margin: 20px 0;">
            <p style="margin: 0;"><strong>Interview:</strong> {stage_name}</p>
            <p style="margin: 10px 0 0;"><strong>Duration:</strong> {duration} minutes</p>
            {% if interviewer_name %}
            <p style="margin: 10px 0 0;"><strong>With:</strong> {interviewer_name}</p>
            {% endif %}
        </div>

        <p>Please click the button below to choose a time that works best for you:</p>

        <p><a href="{booking_url}" style="display: inline-block; background: #1a1a1a; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px;">Choose a Time</a></p>

        <p style="color: #666; font-size: 14px;">This link will expire after you book your slot or after 7 days, whichever comes first.</p>

        <p style="color: #666; font-size: 12px; margin-top: 30px;">
            - The {company_name} Team
        </p>
    </div>
</body>
</html>
''',
            'default_channel': 'email',
            'is_active': True,
        },

        # =================================================================
        # Admin/Custom Notifications
        # =================================================================
        {
            'name': 'Admin Broadcast',
            'description': 'Template for admin broadcast messages',
            'template_type': 'admin_broadcast',
            'is_custom': False,
            'title_template': '{title}',
            'body_template': '{body}',
            'email_subject_template': '{title}',
            'email_body_template': '''
<html>
<body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
    <div style="max-width: 600px; margin: 0 auto; padding: 20px;">
        <h2 style="color: #1a1a1a; margin-bottom: 20px;">{title}</h2>

        <p>Hi {first_name},</p>

        <div style="margin: 20px 0;">
            {body}
        </div>

        {% if action_url %}
        <p><a href="{action_url}" style="display: inline-block; background: #1a1a1a; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px;">Learn More</a></p>
        {% endif %}

        <p style="color: #666; font-size: 12px; margin-top: 30px;">
            - The Oneo Team
        </p>
    </div>
</body>
</html>
''',
            'default_channel': 'both',
            'is_active': True,
        },
        {
            'name': 'Welcome Message',
            'description': 'Welcome message for new users',
            'template_type': 'custom',
            'is_custom': True,
            'title_template': 'Welcome to {company_name}!',
            'body_template': 'Welcome to {company_name}! We\'re excited to have you here.',
            'email_subject_template': 'Welcome to {company_name}!',
            'email_body_template': '''
<html>
<body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
    <div style="max-width: 600px; margin: 0 auto; padding: 20px;">
        <h2 style="color: #1a1a1a; margin-bottom: 20px;">Welcome to {company_name}!</h2>

        <p>Hi {first_name},</p>

        <p>Welcome aboard! We're thrilled to have you as part of our community.</p>

        <p>Here are a few things you can do to get started:</p>
        <ul>
            <li>Complete your profile</li>
            <li>Explore job opportunities</li>
            <li>Connect with our team</li>
        </ul>

        <p>If you have any questions, feel free to reach out. We're here to help!</p>

        <p><a href="{action_url}" style="display: inline-block; background: #1a1a1a; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px;">Get Started</a></p>

        <p style="color: #666; font-size: 12px; margin-top: 30px;">
            - The {company_name} Team
        </p>
    </div>
</body>
</html>
''',
            'default_channel': 'both',
            'is_active': True,
        },
    ]

    for template_data in templates:
        NotificationTemplate.objects.get_or_create(
            name=template_data['name'],
            defaults=template_data
        )


def remove_templates(apps, schema_editor):
    """Remove the seeded templates."""
    NotificationTemplate = apps.get_model('notifications', 'NotificationTemplate')
    NotificationTemplate.objects.filter(is_custom=False).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_templates, remove_templates),
    ]
