# Generated by Django 5.2.9 on 2025-12-05 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_seed_notification_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtemplate',
            name='recipient_type',
            field=models.CharField(choices=[('candidate', 'Candidate'), ('recruiter', 'Recruiter/Hiring Manager'), ('interviewer', 'Interviewer'), ('client', 'Client'), ('all', 'All Users')], default='candidate', help_text='Type of user who receives this notification', max_length=20),
        ),
    ]
