# Generated by Django 5.2.9 on 2025-12-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('welcome', 'Welcome'), ('email_verification', 'Email Verification'), ('password_reset', 'Password Reset'), ('password_changed', 'Password Changed'), ('team_invite', 'Team Member Invitation'), ('client_invite', 'Client Invitation'), ('company_member_invite', 'Company Member Invitation'), ('stage_scheduled', 'Interview Scheduled'), ('stage_reminder', 'Interview Reminder'), ('stage_rescheduled', 'Interview Rescheduled'), ('stage_cancelled', 'Interview Cancelled'), ('stage_completed', 'Interview Completed'), ('stage_feedback_received', 'Interview Feedback Received'), ('booking_link_sent', 'Booking Link Sent'), ('booking_confirmed', 'Booking Confirmed'), ('booking_reminder', 'Booking Reminder'), ('assessment_assigned', 'Assessment Assigned'), ('assessment_reminder', 'Assessment Deadline Reminder'), ('submission_received', 'Submission Received'), ('application_received', 'Application Received'), ('application_shortlisted', 'Application Shortlisted'), ('application_rejected', 'Application Rejected'), ('application_withdrawn', 'Application Withdrawn'), ('advanced_to_application_screen', 'Advanced to Application Screen'), ('advanced_to_phone_screening', 'Advanced to Phone Screening'), ('advanced_to_video_interview', 'Advanced to Video Interview'), ('advanced_to_in_person_interview', 'Advanced to In-Person Interview'), ('advanced_to_take_home_assessment', 'Advanced to Take-Home Assessment'), ('advanced_to_in_person_assessment', 'Advanced to In-Person Assessment'), ('advanced_to_custom_stage', 'Advanced to Next Stage'), ('offer_received', 'Offer Received'), ('offer_accepted', 'Offer Accepted'), ('offer_declined', 'Offer Declined'), ('job_published', 'Job Published'), ('job_closed', 'Job Closed'), ('job_filled', 'Job Filled'), ('job_updated', 'Job Updated'), ('admin_broadcast', 'Admin Broadcast'), ('custom', 'Custom Notification')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='template_type',
            field=models.CharField(blank=True, choices=[('welcome', 'Welcome'), ('email_verification', 'Email Verification'), ('password_reset', 'Password Reset'), ('password_changed', 'Password Changed'), ('team_invite', 'Team Member Invitation'), ('client_invite', 'Client Invitation'), ('company_member_invite', 'Company Member Invitation'), ('stage_scheduled', 'Interview Scheduled'), ('stage_reminder', 'Interview Reminder'), ('stage_rescheduled', 'Interview Rescheduled'), ('stage_cancelled', 'Interview Cancelled'), ('stage_completed', 'Interview Completed'), ('stage_feedback_received', 'Interview Feedback Received'), ('booking_link_sent', 'Booking Link Sent'), ('booking_confirmed', 'Booking Confirmed'), ('booking_reminder', 'Booking Reminder'), ('assessment_assigned', 'Assessment Assigned'), ('assessment_reminder', 'Assessment Deadline Reminder'), ('submission_received', 'Submission Received'), ('application_received', 'Application Received'), ('application_shortlisted', 'Application Shortlisted'), ('application_rejected', 'Application Rejected'), ('application_withdrawn', 'Application Withdrawn'), ('advanced_to_application_screen', 'Advanced to Application Screen'), ('advanced_to_phone_screening', 'Advanced to Phone Screening'), ('advanced_to_video_interview', 'Advanced to Video Interview'), ('advanced_to_in_person_interview', 'Advanced to In-Person Interview'), ('advanced_to_take_home_assessment', 'Advanced to Take-Home Assessment'), ('advanced_to_in_person_assessment', 'Advanced to In-Person Assessment'), ('advanced_to_custom_stage', 'Advanced to Next Stage'), ('offer_received', 'Offer Received'), ('offer_accepted', 'Offer Accepted'), ('offer_declined', 'Offer Declined'), ('job_published', 'Job Published'), ('job_closed', 'Job Closed'), ('job_filled', 'Job Filled'), ('job_updated', 'Job Updated'), ('admin_broadcast', 'Admin Broadcast'), ('custom', 'Custom Notification')], help_text='System notification type this template is for (leave blank for custom)', max_length=50),
        ),
    ]
