# Generated by Django - Add candidate booking invite template

from django.db import migrations, models


def add_template(apps, schema_editor):
    """Add the candidate booking invite template."""
    NotificationTemplate = apps.get_model('notifications', 'NotificationTemplate')

    NotificationTemplate.objects.get_or_create(
        name='Candidate Booking Invitation',
        defaults={
            'description': 'Sent to non-users who book a meeting, inviting them to sign up',
            'template_type': 'candidate_booking_invite',
            'recipient_type': 'candidate',
            'is_custom': False,
            'title_template': 'Complete Your Registration',
            'body_template': 'You have a meeting scheduled with {recruiter_name}. Please complete your registration before {scheduled_at}.',
            'email_subject_template': 'Complete Your Registration Before Your {meeting_type_name}',
            'email_body_template': '''
<html>
<body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
    <div style="max-width: 600px; margin: 0 auto; padding: 20px;">
        <h2 style="color: #1a1a1a; margin-bottom: 20px;">Complete Your Registration</h2>

        <p>Hi {recipient_name},</p>

        <p>You've scheduled a <strong>{meeting_type_name}</strong> with <strong>{recruiter_name}</strong> at <strong>{brand_name}</strong>.</p>

        <div style="background: #f5f5f5; padding: 20px; border-radius: 8px; margin: 20px 0;">
            <p style="margin: 0;"><strong>Meeting:</strong> {meeting_type_name}</p>
            <p style="margin: 10px 0 0;"><strong>Date & Time:</strong> {scheduled_at}</p>
            <p style="margin: 10px 0 0;"><strong>Duration:</strong> {duration_minutes} minutes</p>
            <p style="margin: 10px 0 0;"><strong>With:</strong> {recruiter_name}</p>
        </div>

        <p>To make the most of your meeting, please create your account and complete your profile before your appointment.</p>

        <p><a href="{signup_url}" style="display: inline-block; background: #1a1a1a; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px;">Create Your Account</a></p>

        <p style="color: #666; font-size: 14px; margin-top: 20px;">This will allow the recruiter to review your profile before your meeting and provide a more personalized experience.</p>

        <p>We look forward to meeting you!</p>

        <p style="color: #666; font-size: 12px; margin-top: 30px;">
            - The {brand_name} Team
        </p>
    </div>
</body>
</html>
''',
            'default_channel': 'email',
            'is_active': True,
        }
    )


def remove_template(apps, schema_editor):
    """Remove the template."""
    NotificationTemplate = apps.get_model('notifications', 'NotificationTemplate')
    NotificationTemplate.objects.filter(name='Candidate Booking Invitation').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_remove_application_under_review'),
    ]

    operations = [
        # First update the choices to include candidate_booking_invite
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('welcome', 'Welcome'), ('email_verification', 'Email Verification'), ('password_reset', 'Password Reset'), ('password_changed', 'Password Changed'), ('team_invite', 'Team Member Invitation'), ('client_invite', 'Client Invitation'), ('company_member_invite', 'Company Member Invitation'), ('candidate_booking_invite', 'Candidate Booking Invitation'), ('stage_scheduled', 'Interview Scheduled'), ('stage_reminder', 'Interview Reminder'), ('stage_rescheduled', 'Interview Rescheduled'), ('stage_cancelled', 'Interview Cancelled'), ('stage_completed', 'Interview Completed'), ('stage_feedback_received', 'Interview Feedback Received'), ('booking_link_sent', 'Booking Link Sent'), ('booking_confirmed', 'Booking Confirmed'), ('booking_reminder', 'Booking Reminder'), ('assessment_assigned', 'Assessment Assigned'), ('assessment_reminder', 'Assessment Deadline Reminder'), ('submission_received', 'Submission Received'), ('application_received', 'Application Received'), ('application_shortlisted', 'Application Shortlisted'), ('application_rejected', 'Application Rejected'), ('application_withdrawn', 'Application Withdrawn'), ('advanced_to_application_screen', 'Advanced to Application Screen'), ('advanced_to_phone_screening', 'Advanced to Phone Screening'), ('advanced_to_video_interview', 'Advanced to Video Interview'), ('advanced_to_in_person_interview', 'Advanced to In-Person Interview'), ('advanced_to_take_home_assessment', 'Advanced to Take-Home Assessment'), ('advanced_to_in_person_assessment', 'Advanced to In-Person Assessment'), ('advanced_to_custom_stage', 'Advanced to Next Stage'), ('offer_received', 'Offer Received'), ('offer_accepted', 'Offer Accepted'), ('offer_declined', 'Offer Declined'), ('job_published', 'Job Published'), ('job_closed', 'Job Closed'), ('job_filled', 'Job Filled'), ('job_updated', 'Job Updated'), ('admin_broadcast', 'Admin Broadcast'), ('custom', 'Custom Notification')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='template_type',
            field=models.CharField(blank=True, choices=[('welcome', 'Welcome'), ('email_verification', 'Email Verification'), ('password_reset', 'Password Reset'), ('password_changed', 'Password Changed'), ('team_invite', 'Team Member Invitation'), ('client_invite', 'Client Invitation'), ('company_member_invite', 'Company Member Invitation'), ('candidate_booking_invite', 'Candidate Booking Invitation'), ('stage_scheduled', 'Interview Scheduled'), ('stage_reminder', 'Interview Reminder'), ('stage_rescheduled', 'Interview Rescheduled'), ('stage_cancelled', 'Interview Cancelled'), ('stage_completed', 'Interview Completed'), ('stage_feedback_received', 'Interview Feedback Received'), ('booking_link_sent', 'Booking Link Sent'), ('booking_confirmed', 'Booking Confirmed'), ('booking_reminder', 'Booking Reminder'), ('assessment_assigned', 'Assessment Assigned'), ('assessment_reminder', 'Assessment Deadline Reminder'), ('submission_received', 'Submission Received'), ('application_received', 'Application Received'), ('application_shortlisted', 'Application Shortlisted'), ('application_rejected', 'Application Rejected'), ('application_withdrawn', 'Application Withdrawn'), ('advanced_to_application_screen', 'Advanced to Application Screen'), ('advanced_to_phone_screening', 'Advanced to Phone Screening'), ('advanced_to_video_interview', 'Advanced to Video Interview'), ('advanced_to_in_person_interview', 'Advanced to In-Person Interview'), ('advanced_to_take_home_assessment', 'Advanced to Take-Home Assessment'), ('advanced_to_in_person_assessment', 'Advanced to In-Person Assessment'), ('advanced_to_custom_stage', 'Advanced to Next Stage'), ('offer_received', 'Offer Received'), ('offer_accepted', 'Offer Accepted'), ('offer_declined', 'Offer Declined'), ('job_published', 'Job Published'), ('job_closed', 'Job Closed'), ('job_filled', 'Job Filled'), ('job_updated', 'Job Updated'), ('admin_broadcast', 'Admin Broadcast'), ('custom', 'Custom Notification')], help_text='System notification type this template is for (leave blank for custom)', max_length=50),
        ),
        # Then add the template
        migrations.RunPython(add_template, remove_template),
    ]
