# Generated by Django 5.2.9 on 2025-12-18 21:43

import datetime
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0015_add_headhunting_csuite_placement_fee'),
        ('companies', '0012_add_service_type'),
        ('jobs', '0020_add_shortlist_questions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPricing',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monthly_retainer', models.DecimalField(blank=True, decimal_places=2, help_text='Custom monthly retainer fee (default: R20,000)', max_digits=12, null=True)),
                ('placement_fee', models.DecimalField(blank=True, decimal_places=4, help_text='Custom placement fee as decimal (e.g., 0.10 = 10%)', max_digits=5, null=True)),
                ('csuite_placement_fee', models.DecimalField(blank=True, decimal_places=4, help_text='Custom C-Suite placement fee as decimal (e.g., 0.15 = 15%)', max_digits=5, null=True)),
                ('effective_from', models.DateField(default=datetime.date.today, help_text='When this pricing becomes effective')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_pricing', to='companies.company')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pricing_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company Pricing',
                'verbose_name_plural': 'Company Pricing',
                'db_table': 'company_pricing',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(help_text='Auto-generated format: INV-YYYYMM-XXXX', max_length=50, unique=True)),
                ('invoice_type', models.CharField(choices=[('retainer', 'Monthly Retainer'), ('placement', 'Placement Fee'), ('termination', 'Early Termination Fee'), ('adjustment', 'Adjustment'), ('other', 'Other')], max_length=20)),
                ('billing_mode', models.CharField(choices=[('in_system', 'In-System Billing'), ('external', 'External Tracking Only')], default='in_system', max_length=20)),
                ('invoice_date', models.DateField(help_text='Date the invoice was issued')),
                ('due_date', models.DateField(help_text='Payment due date')),
                ('billing_period_start', models.DateField(blank=True, help_text='Start of billing period (for retainer invoices)', null=True)),
                ('billing_period_end', models.DateField(blank=True, help_text='End of billing period (for retainer invoices)', null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Amount before VAT', max_digits=12)),
                ('vat_rate', models.DecimalField(decimal_places=4, default=Decimal('0.15'), help_text='VAT rate as decimal (0.15 = 15%)', max_digits=5)),
                ('vat_amount', models.DecimalField(decimal_places=2, help_text='VAT amount', max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total amount including VAT', max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total amount paid against this invoice', max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled'), ('partially_paid', 'Partially Paid')], default='draft', max_length=20)),
                ('external_invoice_number', models.CharField(blank=True, help_text='Reference number from external accounting system', max_length=100)),
                ('external_system', models.CharField(blank=True, help_text='Name of external system (e.g., Xero, QuickBooks)', max_length=100)),
                ('sent_at', models.DateTimeField(blank=True, help_text='When the invoice was sent to the client', null=True)),
                ('paid_at', models.DateTimeField(blank=True, help_text='When the invoice was fully paid', null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='When the invoice was cancelled', null=True)),
                ('pdf_file', models.FileField(blank=True, help_text='Generated PDF invoice file', null=True, upload_to='invoices/')),
                ('description', models.TextField(blank=True, help_text='Description shown on the invoice')),
                ('internal_notes', models.TextField(blank=True, help_text='Internal admin notes (not shown on invoice)')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'db_table': 'invoices',
                'ordering': ['-invoice_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(help_text='Description of the line item', max_length=500)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total amount (quantity * unit_price)', max_digits=12)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order of line items')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='subscriptions.invoice')),
                ('placement', models.ForeignKey(blank=True, help_text='Linked placement for placement fee invoices', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='jobs.application')),
            ],
            options={
                'verbose_name': 'Invoice Line Item',
                'verbose_name_plural': 'Invoice Line Items',
                'db_table': 'invoice_line_items',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=12)),
                ('payment_date', models.DateField(help_text='Date the payment was received')),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer (EFT)'), ('credit_card', 'Credit Card'), ('debit_order', 'Debit Order'), ('cash', 'Cash'), ('cheque', 'Cheque'), ('other', 'Other')], max_length=20)),
                ('reference_number', models.CharField(blank=True, help_text='Bank reference, transaction ID, etc.', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this payment')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subscriptions.invoice')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payments',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_start_date', models.DateField(help_text='Start date of the subscription contract')),
                ('contract_end_date', models.DateField(help_text='End date of the subscription contract (typically 1 year from start)')),
                ('billing_day_of_month', models.PositiveSmallIntegerField(default=1, help_text='Day of month for auto-generating retainer invoices (1-28)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)])),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('terminated', 'Terminated'), ('expired', 'Expired')], default='active', max_length=20)),
                ('auto_renew', models.BooleanField(default=True, help_text='Automatically renew the subscription at contract end')),
                ('renewal_reminder_sent', models.BooleanField(default=False, help_text='Whether renewal reminder has been sent for current period')),
                ('terminated_at', models.DateTimeField(blank=True, help_text='When the termination was processed', null=True)),
                ('termination_type', models.CharField(blank=True, choices=[('for_cause', 'For Cause'), ('without_cause', 'Without Cause'), ('mutual', 'Mutual Agreement'), ('expired', 'Contract Expired')], max_length=20)),
                ('termination_reason', models.CharField(blank=True, choices=[('material_breach', 'Material Breach'), ('liquidation', 'Liquidation/Business Rescue'), ('non_payment', 'Non-Payment (30+ days overdue)'), ('client_request', 'Client Request (Early Termination)'), ('contract_expired', 'Contract Expired'), ('mutual_agreement', 'Mutual Agreement')], max_length=30)),
                ('termination_notes', models.TextField(blank=True, help_text='Additional notes about the termination')),
                ('termination_effective_date', models.DateField(blank=True, help_text='Date when termination takes effect', null=True)),
                ('early_termination_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Calculated early termination fee if applicable', max_digits=12, null=True)),
                ('access_expires_at', models.DateTimeField(blank=True, help_text='When platform access should be revoked post-termination', null=True)),
                ('paused_at', models.DateTimeField(blank=True, help_text='When the subscription was paused', null=True)),
                ('pause_reason', models.TextField(blank=True, help_text='Reason for pausing the subscription')),
                ('internal_notes', models.TextField(blank=True, help_text='Internal admin notes about this subscription')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='companies.company')),
                ('paused_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paused_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('terminated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminated_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'db_table': 'subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='subscriptions.subscription'),
        ),
        migrations.CreateModel(
            name='SubscriptionActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('subscription_created', 'Subscription Created'), ('subscription_activated', 'Subscription Activated'), ('subscription_paused', 'Subscription Paused'), ('subscription_resumed', 'Subscription Resumed'), ('subscription_terminated', 'Subscription Terminated'), ('subscription_renewed', 'Subscription Renewed'), ('subscription_expired', 'Subscription Expired'), ('contract_extended', 'Contract Extended'), ('auto_renew_changed', 'Auto-Renew Setting Changed'), ('pricing_changed', 'Pricing Changed'), ('feature_override_added', 'Feature Override Added'), ('feature_override_removed', 'Feature Override Removed'), ('feature_override_changed', 'Feature Override Changed'), ('invoice_created', 'Invoice Created'), ('invoice_sent', 'Invoice Sent'), ('invoice_paid', 'Invoice Paid'), ('invoice_partially_paid', 'Invoice Partially Paid'), ('invoice_cancelled', 'Invoice Cancelled'), ('invoice_overdue', 'Invoice Marked Overdue'), ('payment_recorded', 'Payment Recorded'), ('payment_deleted', 'Payment Deleted')], max_length=30)),
                ('previous_status', models.CharField(blank=True, help_text='Previous status before the change', max_length=20)),
                ('new_status', models.CharField(blank=True, help_text='New status after the change', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context: pricing changes, termination details, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_activities', to='companies.company')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='subscriptions.invoice')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_activities', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='subscriptions.subscription')),
            ],
            options={
                'verbose_name': 'Subscription Activity',
                'verbose_name_plural': 'Subscription Activities',
                'db_table': 'subscription_activity_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyFeatureOverride',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_enabled', models.BooleanField(help_text='True to enable, False to disable (overrides service type default)')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_overrides', to='companies.company')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_overrides', to='cms.pricingfeature')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feature Override',
                'verbose_name_plural': 'Feature Overrides',
                'db_table': 'company_feature_overrides',
                'unique_together': {('company', 'feature')},
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['company', '-invoice_date'], name='invoices_company_36a3e7_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', 'due_date'], name='invoices_status_73cf28_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='invoices_invoice_7778bc_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionactivitylog',
            index=models.Index(fields=['company', '-created_at'], name='subscriptio_company_439072_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionactivitylog',
            index=models.Index(fields=['subscription', '-created_at'], name='subscriptio_subscri_17baa6_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionactivitylog',
            index=models.Index(fields=['activity_type'], name='subscriptio_activit_671761_idx'),
        ),
    ]
