# Generated by Django 5.2.9 on 2025-12-19 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0020_add_shortlist_questions'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='placement',
            field=models.ForeignKey(blank=True, help_text='For placement fee invoices, the associated application/placement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='jobs.application'),
        ),
    ]
