# Generated by Django 5.2.9 on 2025-12-19 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_add_csuite_and_placement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionactivitylog',
            name='activity_type',
            field=models.CharField(choices=[('subscription_created', 'Subscription Created'), ('subscription_activated', 'Subscription Activated'), ('subscription_paused', 'Subscription Paused'), ('subscription_resumed', 'Subscription Resumed'), ('subscription_terminated', 'Subscription Terminated'), ('subscription_renewed', 'Subscription Renewed'), ('subscription_expired', 'Subscription Expired'), ('contract_extended', 'Contract Extended'), ('auto_renew_changed', 'Auto-Renew Setting Changed'), ('service_type_changed', 'Service Type Changed'), ('pricing_changed', 'Pricing Changed'), ('feature_override_added', 'Feature Override Added'), ('feature_override_removed', 'Feature Override Removed'), ('feature_override_changed', 'Feature Override Changed'), ('invoice_created', 'Invoice Created'), ('invoice_sent', 'Invoice Sent'), ('invoice_paid', 'Invoice Paid'), ('invoice_partially_paid', 'Invoice Partially Paid'), ('invoice_cancelled', 'Invoice Cancelled'), ('invoice_overdue', 'Invoice Marked Overdue'), ('payment_recorded', 'Payment Recorded'), ('payment_deleted', 'Payment Deleted')], max_length=30),
        ),
    ]
