# Generated by Django 5.2.9 on 2025-12-20 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_subscriptionactivitylog_activity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(blank=True, help_text='Payment due date (defaults to 14 days from invoice date)', null=True),
        ),
    ]
