# Generated by Django 5.2.9 on 2025-12-20 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_add_service_type'),
        ('subscriptions', '0004_add_default_payment_terms'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='service_type',
            field=models.CharField(choices=[('retained', 'Retained Recruitment'), ('headhunting', 'Headhunting'), ('eor', 'Employer of Record')], default='retained', help_text='The service this subscription/contract is for', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='companies.company'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('company', 'service_type'), name='unique_company_service_type'),
        ),
    ]
