# Generated by Django 5.2.9 on 2025-12-22 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0023_add_replacement_fields'),
        ('subscriptions', '0005_add_service_type_to_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyfeatureoverride',
            name='custom_replacement_period_days',
            field=models.PositiveIntegerField(blank=True, help_text='Custom replacement period for this company in days (overrides service type default). Only used for free-replacements feature.', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_replacement',
            field=models.BooleanField(default=False, help_text='True if this is an invoice for a replacement hire'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='original_placement_invoice',
            field=models.ForeignKey(blank=True, help_text="Link to the original hire's placement invoice", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_invoices', to='subscriptions.invoice'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='replacement_request',
            field=models.ForeignKey(blank=True, help_text='The replacement request that led to this invoice', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='jobs.replacementrequest'),
        ),
    ]
