# Generated by Django 5.2.9 on 2025-12-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_add_replacement_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='companypricing',
            name='replacement_period_days',
            field=models.PositiveIntegerField(blank=True, help_text='Custom replacement period in days (overrides service type default)', null=True),
        ),
    ]
