# Generated by Django 5.2.9 on 2025-12-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_add_replacement_period_to_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='payment_terms_days',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Custom payment terms override in days. If null, uses CMS defaults per invoice type.', null=True),
        ),
    ]
