# Generated by Django 5.2.9 on 2025-12-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_add_custom_payment_terms_to_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pending Approval'), ('active', 'Active'), ('paused', 'Paused'), ('terminated', 'Terminated'), ('expired', 'Expired')], default='active', max_length=20),
        ),
    ]
