# Generated by Django 5.2.9 on 2026-01-01 10:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0011_task_activity_and_notes'),
        ('notifications', '0012_add_rule_execution_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BottleneckRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('entity_type', models.CharField(choices=[('lead', 'Lead'), ('company', 'Company'), ('candidate', 'Candidate'), ('application', 'Application'), ('task', 'Task')], max_length=20)),
                ('bottleneck_type', models.CharField(choices=[('threshold', 'Threshold Exceeded'), ('count', 'Count Exceeded'), ('percentage', 'Percentage Exceeded'), ('duration', 'Duration Exceeded'), ('overdue', 'Overdue')], default='threshold', max_length=20)),
                ('detection_config', models.JSONField(default=dict, help_text='\n        Detection configuration. Examples:\n        - For stage duration: {"type": "stage_duration", "stage_field": "onboarding_stage", "threshold_days": 7}\n        - For count: {"type": "count_in_state", "field": "status", "value": "pending", "threshold_count": 10}\n        - For overdue: {"type": "overdue", "threshold_days": 0}\n        ')),
                ('filter_conditions', models.JSONField(default=list, help_text='Additional filter conditions: [{"field": "priority", "operator": "equals", "value": "high"}]')),
                ('send_notification', models.BooleanField(default=False)),
                ('notification_config', models.JSONField(blank=True, default=dict, help_text='{"recipient_type": "assigned_user", "channel": "both", "title_template": "...", "body_template": "..."}')),
                ('create_task', models.BooleanField(default=False)),
                ('task_config', models.JSONField(blank=True, default=dict, help_text='{"title_template": "Follow up: {{name}}", "priority": "high", "due_days": 1, "assign_to": "entity_owner"}')),
                ('cooldown_hours', models.PositiveIntegerField(default=24, help_text='Hours before same entity can trigger this rule again')),
                ('is_active', models.BooleanField(default=True)),
                ('run_on_schedule', models.BooleanField(default=True, help_text='Run automatically via Celery Beat')),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('total_detections', models.PositiveIntegerField(default=0)),
                ('total_notifications_sent', models.PositiveIntegerField(default=0)),
                ('total_tasks_created', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bottleneck_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bottleneck Rule',
                'verbose_name_plural': 'Bottleneck Rules',
                'db_table': 'bottleneck_rules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BottleneckDetection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=20)),
                ('entity_id', models.CharField(max_length=50)),
                ('detection_data', models.JSONField(default=dict, help_text='Snapshot of detection context: {"days_in_stage": 12, "stage_name": "Qualified", ...}')),
                ('notification_sent', models.BooleanField(default=False)),
                ('task_created', models.BooleanField(default=False)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bottleneck_detections', to='notifications.notification')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_bottlenecks', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bottleneck_detections', to='core.task')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='bottlenecks.bottleneckrule')),
            ],
            options={
                'verbose_name': 'Bottleneck Detection',
                'verbose_name_plural': 'Bottleneck Detections',
                'db_table': 'bottleneck_detections',
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['rule', 'entity_type', 'entity_id', '-detected_at'], name='bottleneck__rule_id_12f5af_idx'), models.Index(fields=['is_resolved', '-detected_at'], name='bottleneck__is_reso_699d23_idx'), models.Index(fields=['entity_type', 'entity_id'], name='bottleneck__entity__0b20d6_idx')],
            },
        ),
    ]
