# Generated by Django 5.2.9 on 2026-01-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottlenecks', '0002_seed_default_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottleneckrule',
            name='next_run_at',
            field=models.DateTimeField(blank=True, help_text='When this rule should next be executed', null=True),
        ),
        migrations.AddField(
            model_name='bottleneckrule',
            name='schedule_interval_minutes',
            field=models.PositiveIntegerField(default=60, help_text='How often to run this rule (in minutes). Common values: 15, 30, 60, 240, 1440 (daily)'),
        ),
        migrations.AlterField(
            model_name='bottleneckrule',
            name='entity_type',
            field=models.CharField(choices=[('lead', 'Lead'), ('company', 'Company'), ('candidate', 'Candidate'), ('application', 'Application'), ('stage_instance', 'Interview Stage'), ('task', 'Task')], max_length=20),
        ),
    ]
