# Generated by Django 5.2.9 on 2026-01-01 14:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottlenecks', '0004_seed_comprehensive_rules'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BottleneckRuleExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger', models.CharField(choices=[('scheduled', 'Scheduled'), ('manual', 'Manual'), ('api', 'API Call')], default='scheduled', max_length=20)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, help_text='Execution duration in milliseconds', null=True)),
                ('entities_scanned', models.PositiveIntegerField(default=0)),
                ('entities_matched', models.PositiveIntegerField(default=0)),
                ('entities_in_cooldown', models.PositiveIntegerField(default=0)),
                ('detections_created', models.PositiveIntegerField(default=0)),
                ('notifications_sent', models.PositiveIntegerField(default=0)),
                ('tasks_created', models.PositiveIntegerField(default=0)),
                ('matched_entity_ids', models.JSONField(default=list, help_text='List of entity IDs that matched this run')),
                ('rule_config_snapshot', models.JSONField(default=dict, help_text='Snapshot of detection_config and filter_conditions at execution time')),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='bottlenecks.bottleneckrule')),
                ('triggered_by', models.ForeignKey(blank=True, help_text='User who triggered manual execution (null for scheduled)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_bottleneck_executions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rule Execution',
                'verbose_name_plural': 'Rule Executions',
                'db_table': 'bottleneck_rule_executions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='bottleneckdetection',
            name='execution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detections', to='bottlenecks.bottleneckruleexecution'),
        ),
        migrations.AddIndex(
            model_name='bottleneckruleexecution',
            index=models.Index(fields=['rule', '-started_at'], name='bottleneck__rule_id_d80d30_idx'),
        ),
        migrations.AddIndex(
            model_name='bottleneckruleexecution',
            index=models.Index(fields=['-started_at'], name='bottleneck__started_78d4fc_idx'),
        ),
    ]
