# Generated by Django 5.2.9 on 2026-01-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottlenecks', '0005_add_execution_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottleneckdetection',
            name='current_value',
            field=models.FloatField(blank=True, help_text='Current value (e.g., days in stage, days overdue)', null=True),
        ),
        migrations.AddField(
            model_name='bottleneckdetection',
            name='projected_breach_at',
            field=models.DateTimeField(blank=True, help_text='Projected time when threshold will be breached (for warnings)', null=True),
        ),
        migrations.AddField(
            model_name='bottleneckdetection',
            name='severity',
            field=models.CharField(choices=[('warning', 'Warning'), ('critical', 'Critical')], default='critical', help_text='Warning = approaching threshold, Critical = threshold exceeded', max_length=10),
        ),
        migrations.AddField(
            model_name='bottleneckdetection',
            name='threshold_value',
            field=models.FloatField(blank=True, help_text='Threshold value that triggers critical detection', null=True),
        ),
        migrations.AddField(
            model_name='bottleneckrule',
            name='enable_warnings',
            field=models.BooleanField(default=False, help_text='Enable warning detections for entities approaching the threshold'),
        ),
        migrations.AddField(
            model_name='bottleneckrule',
            name='warning_threshold_percentage',
            field=models.PositiveIntegerField(default=80, help_text='Percentage of threshold at which to create warning detections (e.g., 80 = warn at 80% of threshold)'),
        ),
    ]
