# Generated by Django 5.2.9 on 2026-01-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottlenecks', '0006_add_warning_threshold_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottleneckdetection',
            name='resolution_notes',
            field=models.TextField(blank=True, default='', help_text='Notes about how this detection was resolved (manual or auto)'),
        ),
    ]
