# Generated by Django 5.2.9 on 2025-12-19 20:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0012_add_service_type'),
        ('subscriptions', '0003_alter_subscriptionactivitylog_activity_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='XeroConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_token', models.TextField(help_text='OAuth access token (should be encrypted in production)')),
                ('refresh_token', models.TextField(help_text='OAuth refresh token')),
                ('token_expires_at', models.DateTimeField(help_text='When the access token expires')),
                ('tenant_id', models.CharField(help_text='Xero Tenant ID (organization identifier)', max_length=255, unique=True)),
                ('tenant_name', models.CharField(help_text='Xero organization name', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this connection is active')),
                ('last_sync_at', models.DateTimeField(blank=True, help_text='Last successful payment sync timestamp', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connected_by', models.ForeignKey(blank=True, help_text='User who connected the Xero account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xero_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Xero Connection',
                'verbose_name_plural': 'Xero Connections',
                'db_table': 'xero_connections',
            },
        ),
        migrations.CreateModel(
            name='XeroContactMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('xero_contact_id', models.CharField(help_text='Xero Contact ID', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='xero_contact', to='companies.company')),
            ],
            options={
                'verbose_name': 'Xero Contact Mapping',
                'verbose_name_plural': 'Xero Contact Mappings',
                'db_table': 'xero_contact_mappings',
            },
        ),
        migrations.CreateModel(
            name='XeroPaymentMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('xero_payment_id', models.CharField(help_text='Xero Payment ID', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='xero_mapping', to='subscriptions.payment')),
            ],
            options={
                'verbose_name': 'Xero Payment Mapping',
                'verbose_name_plural': 'Xero Payment Mappings',
                'db_table': 'xero_payment_mappings',
            },
        ),
        migrations.CreateModel(
            name='XeroInvoiceMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('xero_invoice_id', models.CharField(help_text='Xero Invoice ID', max_length=255)),
                ('xero_invoice_number', models.CharField(blank=True, help_text='Invoice number assigned by Xero', max_length=50)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('error', 'Error')], default='pending', max_length=20)),
                ('sync_error', models.TextField(blank=True, help_text='Error message if sync failed')),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='Last successful sync timestamp', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='xero_mapping', to='subscriptions.invoice')),
            ],
            options={
                'verbose_name': 'Xero Invoice Mapping',
                'verbose_name_plural': 'Xero Invoice Mappings',
                'db_table': 'xero_invoice_mappings',
                'indexes': [models.Index(fields=['xero_invoice_id'], name='xero_invoic_xero_in_451bd6_idx'), models.Index(fields=['sync_status'], name='xero_invoic_sync_st_803d83_idx')],
            },
        ),
    ]
