# Generated by Django 5.2.9 on 2025-12-11 12:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('meta_title', models.CharField(blank=True, help_text='SEO title (max 70 chars)', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='SEO description (max 160 chars)', max_length=160)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='cms/og/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('content', models.JSONField(blank=True, default=dict, help_text='Editor.js JSON blocks')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('excerpt', models.TextField(blank=True, help_text='Short summary for listings')),
                ('client_name', models.CharField(blank=True, help_text='Can be anonymized', max_length=200)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('highlights', models.JSONField(blank=True, default=list, help_text='Key metrics as [{label: string, value: string}]')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='cms/case-studies/')),
                ('client_logo', models.ImageField(blank=True, null=True, upload_to='cms/case-studies/logos/')),
                ('testimonial_quote', models.TextField(blank=True)),
                ('testimonial_author', models.CharField(blank=True, max_length=200)),
                ('testimonial_role', models.CharField(blank=True, max_length=200)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Case Studies',
                'db_table': 'cms_case_studies',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('source_page', models.CharField(blank=True, help_text='Page where form was submitted', max_length=200)),
                ('is_read', models.BooleanField(default=False)),
                ('is_replied', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, help_text='Internal notes')),
            ],
            options={
                'db_table': 'cms_contact_submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'FAQ Categories',
                'db_table': 'cms_faq_categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(blank=True, help_text='Where they signed up', max_length=100)),
            ],
            options={
                'db_table': 'cms_newsletter_subscribers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('meta_title', models.CharField(blank=True, help_text='SEO title (max 70 chars)', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='SEO description (max 160 chars)', max_length=160)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='cms/og/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('content', models.JSONField(blank=True, default=dict, help_text='Editor.js JSON blocks')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('excerpt', models.TextField(blank=True, help_text='Short summary for listings')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='cms/blog/')),
                ('featured_image_alt', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_featured', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cms_blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cms_blog_posts',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.JSONField(blank=True, default=dict, help_text='Editor.js JSON blocks')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=500)),
                ('answer_plain', models.TextField(blank=True, help_text='Plain text for SEO/search')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show in highlights/homepage')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faqs', to='cms.faqcategory')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'db_table': 'cms_faqs',
                'ordering': ['category__order', 'order'],
            },
        ),
        migrations.CreateModel(
            name='GlossaryTerm',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('meta_title', models.CharField(blank=True, help_text='SEO title (max 70 chars)', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='SEO description (max 160 chars)', max_length=160)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='cms/og/')),
                ('content', models.JSONField(blank=True, default=dict, help_text='Editor.js JSON blocks')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('definition_plain', models.TextField(blank=True, help_text='Plain text for SEO/search')),
                ('is_active', models.BooleanField(default=True)),
                ('related_terms', models.ManyToManyField(blank=True, to='cms.glossaryterm')),
            ],
            options={
                'db_table': 'cms_glossary_terms',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('meta_title', models.CharField(blank=True, help_text='SEO title (max 70 chars)', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='SEO description (max 160 chars)', max_length=160)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='cms/og/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('content', models.JSONField(blank=True, default=dict, help_text='Editor.js JSON blocks')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_type', models.CharField(choices=[('legal', 'Legal'), ('about', 'About'), ('service', 'Service'), ('generic', 'Generic')], default='generic', max_length=20)),
                ('excerpt', models.TextField(blank=True, help_text='Short description for previews')),
                ('show_in_navigation', models.BooleanField(default=False)),
                ('navigation_order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cms_pages_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cms_pages_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cms_pages',
                'ordering': ['navigation_order', 'title'],
            },
        ),
    ]
