# Generated by Django 5.2.9 on 2025-12-11 13:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ga_measurement_id', models.CharField(blank=True, help_text='Google Analytics 4 Measurement ID (e.g., G-XXXXXXXXXX)', max_length=50)),
                ('gtm_container_id', models.CharField(blank=True, help_text='Google Tag Manager Container ID (e.g., GTM-XXXXXXX)', max_length=50)),
                ('enable_analytics', models.BooleanField(default=True, help_text='Enable/disable analytics tracking globally')),
                ('robots_txt_content', models.TextField(blank=True, default='User-agent: *\nAllow: /\nAllow: /jobs\nAllow: /candidates\nAllow: /companies\nAllow: /blog\nAllow: /pages\nAllow: /contact\n\nDisallow: /dashboard\nDisallow: /api\nDisallow: /login\nDisallow: /signup\nDisallow: /settings\n\nSitemap: https://oneo.com/sitemap.xml', help_text='Content of robots.txt file')),
                ('llms_txt_content', models.TextField(blank=True, help_text='Content of llms.txt file for AI/LLM agents')),
                ('sitemap_enabled', models.BooleanField(default=True)),
                ('sitemap_include_pages', models.BooleanField(default=True)),
                ('sitemap_include_blog', models.BooleanField(default=True)),
                ('sitemap_include_jobs', models.BooleanField(default=True)),
                ('sitemap_include_candidates', models.BooleanField(default=True)),
                ('sitemap_include_companies', models.BooleanField(default=True)),
                ('sitemap_include_glossary', models.BooleanField(default=True)),
                ('sitemap_include_case_studies', models.BooleanField(default=True)),
                ('site_name', models.CharField(default='Oneo', max_length=100)),
                ('site_url', models.URLField(default='https://oneo.com')),
                ('site_description', models.TextField(blank=True, default='Oneo is a modern recruitment platform that connects talented candidates with great companies.')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
