# Generated by Django 5.2.9 on 2025-12-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_add_site_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='page',
            name='excerpt',
        ),
        migrations.RemoveField(
            model_name='page',
            name='navigation_order',
        ),
        migrations.RemoveField(
            model_name='page',
            name='page_type',
        ),
        migrations.RemoveField(
            model_name='page',
            name='show_in_navigation',
        ),
        migrations.AddField(
            model_name='page',
            name='document_type',
            field=models.CharField(choices=[('terms', 'Terms & Conditions'), ('privacy', 'Privacy Policy'), ('cookies', 'Cookie Policy'), ('acceptable_use', 'Acceptable Use Policy'), ('other', 'Other Legal Document')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='page',
            name='effective_date',
            field=models.DateField(blank=True, help_text='When this version takes effect', null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='version',
            field=models.CharField(blank=True, help_text='e.g., 1.0, 2.1', max_length=20),
        ),
    ]
