# Generated by Django 5.2.9 on 2025-12-12 04:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_legal_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='HtaccessRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Descriptive name for this rule', max_length=100)),
                ('rule_content', models.TextField(help_text='Apache .htaccess directive(s)')),
                ('description', models.TextField(blank=True, help_text='Explanation of what this rule does')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which rules are applied (lower = first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cms_htaccess_rules',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MetaTagDefaults',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('default_title_suffix', models.CharField(default=' | Oneo', help_text="Appended to all page titles (e.g., ' | Oneo')", max_length=100)),
                ('default_description', models.TextField(blank=True, help_text="Default meta description when page doesn't have one")),
                ('default_og_image', models.ImageField(blank=True, help_text='Default Open Graph image for social sharing', null=True, upload_to='cms/seo/')),
                ('google_site_verification', models.CharField(blank=True, help_text='Google Search Console verification code', max_length=100)),
                ('bing_site_verification', models.CharField(blank=True, help_text='Bing Webmaster Tools verification code', max_length=100)),
                ('google_analytics_id', models.CharField(blank=True, help_text='Google Analytics measurement ID (e.g., G-XXXXXXXXXX)', max_length=50)),
                ('google_tag_manager_id', models.CharField(blank=True, help_text='Google Tag Manager container ID (e.g., GTM-XXXXXXX)', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Meta Tag Defaults',
                'verbose_name_plural': 'Meta Tag Defaults',
                'db_table': 'cms_meta_tag_defaults',
            },
        ),
        migrations.CreateModel(
            name='RobotsTxt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(default='User-agent: *\nAllow: /\n\nSitemap: https://example.com/sitemap.xml', help_text='Content for robots.txt file')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Robots.txt',
                'verbose_name_plural': 'Robots.txt',
                'db_table': 'cms_robots_txt',
            },
        ),
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_path', models.CharField(help_text='Path to redirect from (e.g., /old-page)', max_length=500)),
                ('destination_url', models.CharField(help_text='URL to redirect to (e.g., /new-page or https://example.com/page)', max_length=500)),
                ('redirect_type', models.CharField(choices=[('301', '301 Permanent'), ('302', '302 Temporary')], default='301', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('is_regex', models.BooleanField(default=False, help_text='Treat source path as a regular expression')),
                ('hit_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cms_redirects',
                'ordering': ['source_path'],
                'unique_together': {('source_path',)},
            },
        ),
    ]
