# Generated by Django 5.2.9 on 2025-12-12 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_seo_models'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HtaccessRule',
        ),
    ]
