# Generated by Django 5.2.9 on 2025-12-12 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_remove_htaccess_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='redirect',
            name='is_auto_generated',
            field=models.BooleanField(default=False, help_text='True if automatically created from slug change'),
        ),
        migrations.AlterField(
            model_name='redirect',
            name='destination_url',
            field=models.CharField(blank=True, default='', help_text='URL to redirect to (leave empty for 410 Gone)', max_length=500),
        ),
        migrations.AlterField(
            model_name='redirect',
            name='redirect_type',
            field=models.CharField(choices=[('301', '301 Permanent Redirect'), ('302', '302 Temporary Redirect'), ('410', '410 Gone (Deleted)')], default='301', max_length=3),
        ),
    ]
