# Generated by Django 5.2.9 on 2025-12-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_add_410_and_auto_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='faqs',
            field=models.ManyToManyField(blank=True, help_text='FAQs to display on this blog post', related_name='blog_posts', to='cms.faq'),
        ),
        migrations.AddField(
            model_name='glossaryterm',
            name='faqs',
            field=models.ManyToManyField(blank=True, help_text='FAQs to display on this glossary term', related_name='glossary_terms', to='cms.faq'),
        ),
    ]
