# Generated by Django 5.2.9 on 2025-12-12 09:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_add_faqs_to_blog_and_glossary'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSEO',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.CharField(help_text="URL path (e.g., '/', '/candidates', '/jobs'). Use '*' suffix for pattern matching (e.g., '/jobs/*')", max_length=500, unique=True)),
                ('name', models.CharField(help_text="Friendly name for this page (e.g., 'Home Page', 'Candidates Directory')", max_length=200)),
                ('title', models.CharField(blank=True, help_text='Page title (without suffix). Leave blank to use page name.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Meta description for search engines (max 160 chars recommended)', max_length=320)),
                ('og_image', models.ImageField(blank=True, help_text='Open Graph image for social sharing', null=True, upload_to='cms/seo/pages/')),
                ('noindex', models.BooleanField(default=False, help_text='Prevent search engines from indexing this page')),
                ('canonical_url', models.URLField(blank=True, help_text='Canonical URL if different from the page URL', max_length=500)),
                ('include_in_sitemap', models.BooleanField(default=True, help_text='Include this page in the sitemap')),
                ('sitemap_priority', models.DecimalField(decimal_places=1, default=0.5, help_text='Priority in sitemap (0.0 to 1.0). Higher = more important.', max_digits=2)),
                ('is_active', models.BooleanField(default=True, help_text='Enable SEO settings for this page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page SEO',
                'verbose_name_plural': 'Page SEO Settings',
                'db_table': 'cms_page_seo',
                'ordering': ['path'],
            },
        ),
    ]
