# Generated by Django 5.2.9 on 2025-12-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_page_seo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageseo',
            name='is_system',
            field=models.BooleanField(default=False, help_text='System pages are auto-generated and cannot be deleted'),
        ),
    ]
