# Generated by Django 5.2.9 on 2025-12-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_add_is_system_to_pageseo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageseo',
            name='description_template',
            field=models.TextField(blank=True, help_text="Template for dynamic descriptions. E.g., 'Apply for {{job.title}} at {{job.company_name}}. {{job.summary}}'", max_length=500),
        ),
        migrations.AddField(
            model_name='pageseo',
            name='title_template',
            field=models.CharField(blank=True, help_text="Template for dynamic titles. Use {{variable}} syntax. E.g., '{{job.title}} at {{job.company_name}}'", max_length=300),
        ),
    ]
