# Generated by Django 5.2.9 on 2025-12-12 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_add_seo_templates_to_pageseo'),
    ]

    operations = [
        migrations.AddField(
            model_name='metatagdefaults',
            name='company_name',
            field=models.CharField(default='Oneo', help_text="Company name used in SEO (e.g., 'Oneo')", max_length=100),
        ),
        migrations.AddField(
            model_name='metatagdefaults',
            name='tagline',
            field=models.CharField(blank=True, default='Recruitment Made Simple', help_text="Company tagline (e.g., 'Recruitment Made Simple')", max_length=200),
        ),
        migrations.AlterField(
            model_name='metatagdefaults',
            name='default_title_suffix',
            field=models.CharField(default=' | {{company_name}}', help_text='Appended to all page titles. Use {{company_name}} or {{tagline}} as variables.', max_length=100),
        ),
    ]
