# Generated by Django 5.2.9 on 2025-12-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_add_branding_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metatagdefaults',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='metatagdefaults',
            name='tagline',
        ),
        migrations.AlterField(
            model_name='metatagdefaults',
            name='default_title_suffix',
            field=models.CharField(default=' | {{company_name}}', help_text='Appended to all page titles. Use {{company_name}} or {{tagline}} from Branding settings.', max_length=100),
        ),
    ]
