# Generated by Django 5.2.9 on 2025-12-13 08:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_remove_duplicate_branding_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingFeature',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('recruitment', 'Recruitment'), ('retained', 'Retained'), ('employment', 'Employment'), ('additional', 'Additional')], default='recruitment', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('included_in_enterprise', models.BooleanField(default=True)),
                ('included_in_eor', models.BooleanField(default=False)),
                ('included_in_retained', models.BooleanField(default=False)),
                ('included_in_headhunting', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Pricing Feature',
                'verbose_name_plural': 'Pricing Features',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PricingConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enterprise_markup_year1', models.DecimalField(decimal_places=4, default=0.22, help_text='Year 1 markup rate (e.g., 0.22 = 22%)', max_digits=5)),
                ('enterprise_markup_year2', models.DecimalField(decimal_places=4, default=0.2, help_text='Year 2 markup rate', max_digits=5)),
                ('enterprise_markup_year3', models.DecimalField(decimal_places=4, default=0.18, help_text='Year 3 markup rate', max_digits=5)),
                ('enterprise_markup_year4_plus', models.DecimalField(decimal_places=4, default=0.16, help_text='Year 4+ markup rate', max_digits=5)),
                ('enterprise_additionals_fee', models.DecimalField(decimal_places=4, default=0.12, help_text='Fee on additionals (e.g., 0.12 = 12%)', max_digits=5)),
                ('enterprise_assets_fee', models.DecimalField(decimal_places=4, default=0.12, help_text='Fee on assets (e.g., 0.12 = 12%)', max_digits=5)),
                ('eor_monthly_fee', models.DecimalField(decimal_places=2, default=7000, help_text='Monthly fee per person (ZAR)', max_digits=10)),
                ('eor_additionals_fee', models.DecimalField(decimal_places=4, default=0.2, help_text='Fee on additionals (e.g., 0.20 = 20%)', max_digits=5)),
                ('eor_assets_fee', models.DecimalField(decimal_places=4, default=0.2, help_text='Fee on assets (e.g., 0.20 = 20%)', max_digits=5)),
                ('retained_monthly_retainer', models.DecimalField(decimal_places=2, default=20000, help_text='Monthly retainer fee (ZAR)', max_digits=10)),
                ('retained_placement_fee', models.DecimalField(decimal_places=4, default=0.05, help_text='Placement fee as markup (e.g., 0.05 = 5%)', max_digits=5)),
                ('headhunting_placement_fee', models.DecimalField(decimal_places=4, default=0.2, help_text='Placement fee as markup (e.g., 0.20 = 20%)', max_digits=5)),
                ('default_salary', models.DecimalField(decimal_places=2, default=45000, help_text='Default monthly salary (ZAR)', max_digits=10)),
                ('default_desk_fee', models.DecimalField(decimal_places=2, default=5000, help_text='Default desk/co-working fee per month (ZAR)', max_digits=10)),
                ('default_lunch_fee', models.DecimalField(decimal_places=2, default=500, help_text='Default lunch fee per person per month (ZAR)', max_digits=10)),
                ('default_event_cost', models.DecimalField(decimal_places=2, default=15000, help_text='Default quarterly event cost (ZAR)', max_digits=10)),
                ('default_party_cost', models.DecimalField(decimal_places=2, default=50000, help_text='Default year-end party cost (ZAR)', max_digits=10)),
                ('default_asset_cost', models.DecimalField(decimal_places=2, default=25000, help_text='Default asset cost per hire (ZAR)', max_digits=10)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pricing_config_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pricing Configuration',
                'verbose_name_plural': 'Pricing Configuration',
            },
        ),
    ]
