# Generated by Django 5.2.9 on 2025-12-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_pricingfeature_pricingconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingconfig',
            name='retained_csuite_placement_fee',
            field=models.DecimalField(decimal_places=4, default=0.15, help_text='Placement fee for C-Suite executives (e.g., 0.15 = 15%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='retained_placement_fee',
            field=models.DecimalField(decimal_places=4, default=0.1, help_text='Placement fee for regular employees (e.g., 0.10 = 10%)', max_digits=5),
        ),
    ]
