# Generated by Django 5.2.9 on 2025-12-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_add_retained_csuite_placement_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingconfig',
            name='headhunting_csuite_placement_fee',
            field=models.DecimalField(decimal_places=4, default=0.25, help_text='Placement fee for C-Suite executives (e.g., 0.25 = 25%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='headhunting_placement_fee',
            field=models.DecimalField(decimal_places=4, default=0.2, help_text='Placement fee for regular employees (e.g., 0.20 = 20%)', max_digits=5),
        ),
    ]
