# Generated by Django 5.2.9 on 2025-12-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_add_headhunting_csuite_placement_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='service_type',
            field=models.CharField(choices=[('all', 'All Service Types'), ('retained', 'Retained Only'), ('headhunting', 'Headhunting Only')], default='all', help_text='Which service types this legal document applies to', max_length=20),
        ),
    ]
