# Generated by Django 5.2.9 on 2025-12-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_add_slug_to_pricingfeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingconfig',
            name='enterprise_replacement_period_days',
            field=models.PositiveIntegerField(default=90, help_text='Days within which a free replacement can be requested (Enterprise service)'),
        ),
        migrations.AddField(
            model_name='pricingconfig',
            name='headhunting_replacement_period_days',
            field=models.PositiveIntegerField(default=0, help_text='Days within which a free replacement can be requested (Headhunting). 0 = not available.'),
        ),
        migrations.AddField(
            model_name='pricingconfig',
            name='retained_replacement_period_days',
            field=models.PositiveIntegerField(default=90, help_text='Days within which a free replacement can be requested (Retained service)'),
        ),
    ]
