# Generated by Django 5.2.9 on 2025-12-23 16:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_add_replacement_period_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('available_payment_terms', models.JSONField(default=list, help_text='Available payment term options in days. E.g., [0, 7, 14, 30, 45, 60]')),
                ('retainer_payment_terms_days', models.PositiveSmallIntegerField(default=30, help_text='Default payment terms for monthly retainer invoices')),
                ('placement_payment_terms_days', models.PositiveSmallIntegerField(default=30, help_text='Default payment terms for placement fee invoices')),
                ('termination_payment_terms_days', models.PositiveSmallIntegerField(default=30, help_text='Default payment terms for early termination invoices')),
                ('service_type_change_payment_terms_days', models.PositiveSmallIntegerField(default=7, help_text='Payment terms for service type change fees (blocking payment - requires payment before change)')),
                ('adjustment_payment_terms_days', models.PositiveSmallIntegerField(default=14, help_text='Default payment terms for adjustment invoices')),
                ('other_payment_terms_days', models.PositiveSmallIntegerField(default=14, help_text='Default payment terms for other invoice types')),
                ('default_vat_rate', models.DecimalField(decimal_places=4, default=0.15, help_text='Default VAT rate as decimal (0.15 = 15%)', max_digits=5)),
                ('invoice_number_prefix', models.CharField(default='INV', help_text='Prefix for invoice numbers (e.g., INV-202412-0001)', max_length=10)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_config_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Billing Configuration',
                'verbose_name_plural': 'Billing Configuration',
            },
        ),
    ]
