# Generated by Django 5.2.9 on 2025-12-24 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0019_add_billing_config'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactSubmission',
        ),
    ]
