"""CMS Views."""

from .pages import (
    list_pages,
    get_page,
    create_page,
    update_page,
    delete_page,
    get_public_page,
)
from .blog import (
    list_blog_posts,
    get_blog_post,
    create_blog_post,
    update_blog_post,
    delete_blog_post,
    list_public_blog_posts,
    get_public_blog_post,
    get_blog_categories,
)
from .faqs import (
    list_faq_categories,
    create_faq_category,
    update_faq_category,
    delete_faq_category,
    list_faqs,
    get_faq,
    create_faq,
    update_faq,
    delete_faq,
    get_public_faqs,
    get_featured_faqs,
)
from .glossary import (
    list_glossary_terms,
    get_glossary_term,
    create_glossary_term,
    update_glossary_term,
    delete_glossary_term,
    list_public_glossary_terms,
    get_public_glossary_term,
    get_glossary_alphabet,
)
from .case_studies import (
    list_case_studies,
    get_case_study,
    create_case_study,
    update_case_study,
    delete_case_study,
    list_public_case_studies,
    get_public_case_study,
    get_case_study_industries,
)
from .submissions import (
    list_contact_submissions,
    get_contact_submission,
    update_contact_submission,
    delete_contact_submission,
    submit_contact_form,
    list_newsletter_subscribers,
    delete_newsletter_subscriber,
    subscribe_to_newsletter,
)
from .sitemap import sitemap_xml, sitemap_index, sitemap_by_type, sitemap_xsl
from .site_settings import (
    get_site_settings,
    update_site_settings,
    analytics_settings,
    robots_txt_settings,
    llms_txt_settings,
    sitemap_settings,
    get_public_analytics_settings,
    robots_txt,
    llms_txt,
)
from .seo import (
    list_redirects,
    redirect_detail,
    bulk_delete_redirects,
    meta_tag_defaults,
    get_public_seo_defaults,
    list_page_seo,
    page_seo_detail,
    sync_system_pages,
    get_page_seo_by_path,
    get_all_page_seo_public,
)
from .pricing import (
    get_public_pricing_config,
    list_public_pricing_features,
    get_pricing_config,
    update_pricing_config,
    list_pricing_features,
    pricing_feature_detail,
    reorder_pricing_features,
)

__all__ = [
    # Pages
    'list_pages',
    'get_page',
    'create_page',
    'update_page',
    'delete_page',
    'get_public_page',
    # Blog
    'list_blog_posts',
    'get_blog_post',
    'create_blog_post',
    'update_blog_post',
    'delete_blog_post',
    'list_public_blog_posts',
    'get_public_blog_post',
    'get_blog_categories',
    # FAQs
    'list_faq_categories',
    'create_faq_category',
    'update_faq_category',
    'delete_faq_category',
    'list_faqs',
    'get_faq',
    'create_faq',
    'update_faq',
    'delete_faq',
    'get_public_faqs',
    'get_featured_faqs',
    # Glossary
    'list_glossary_terms',
    'get_glossary_term',
    'create_glossary_term',
    'update_glossary_term',
    'delete_glossary_term',
    'list_public_glossary_terms',
    'get_public_glossary_term',
    'get_glossary_alphabet',
    # Case Studies
    'list_case_studies',
    'get_case_study',
    'create_case_study',
    'update_case_study',
    'delete_case_study',
    'list_public_case_studies',
    'get_public_case_study',
    'get_case_study_industries',
    # Submissions
    'list_contact_submissions',
    'get_contact_submission',
    'update_contact_submission',
    'delete_contact_submission',
    'submit_contact_form',
    'list_newsletter_subscribers',
    'delete_newsletter_subscriber',
    'subscribe_to_newsletter',
    # Sitemap
    'sitemap_xml',
    'sitemap_index',
    'sitemap_by_type',
    'sitemap_xsl',
    # Site Settings
    'get_site_settings',
    'update_site_settings',
    'analytics_settings',
    'robots_txt_settings',
    'llms_txt_settings',
    'sitemap_settings',
    'get_public_analytics_settings',
    'robots_txt',
    'llms_txt',
    # SEO
    'list_redirects',
    'redirect_detail',
    'bulk_delete_redirects',
    'meta_tag_defaults',
    'get_public_seo_defaults',
    'list_page_seo',
    'page_seo_detail',
    'sync_system_pages',
    'get_page_seo_by_path',
    'get_all_page_seo_public',
    # Pricing
    'get_public_pricing_config',
    'list_public_pricing_features',
    'get_pricing_config',
    'update_pricing_config',
    'list_pricing_features',
    'pricing_feature_detail',
    'reorder_pricing_features',
]
