# Generated by Django 5.2.9 on 2025-12-04 21:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCalendarConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('google', 'Google Calendar'), ('microsoft', 'Microsoft 365')], max_length=20)),
                ('access_token', models.TextField(help_text='OAuth access token (encrypted)')),
                ('refresh_token', models.TextField(blank=True, help_text='OAuth refresh token (encrypted)')),
                ('token_expires_at', models.DateTimeField(blank=True, help_text='When the access token expires', null=True)),
                ('provider_user_id', models.CharField(blank=True, help_text='User ID from the calendar provider', max_length=255)),
                ('provider_email', models.EmailField(blank=True, help_text='Email associated with the calendar account', max_length=254)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this connection is active')),
                ('calendar_id', models.CharField(default='primary', help_text='Which calendar to use (primary or specific calendar ID)', max_length=255)),
                ('calendar_name', models.CharField(blank=True, default='', help_text='Display name of the selected calendar', max_length=255)),
                ('booking_days_ahead', models.PositiveIntegerField(default=14, help_text='How many days in advance bookings are allowed')),
                ('business_hours_start', models.PositiveSmallIntegerField(default=9, help_text='Start hour for availability (0-23)')),
                ('business_hours_end', models.PositiveSmallIntegerField(default=18, help_text='End hour for availability (0-23)')),
                ('min_notice_hours', models.PositiveIntegerField(default=24, help_text='Minimum hours notice required before booking')),
                ('buffer_minutes', models.PositiveIntegerField(default=0, help_text='Buffer time between meetings in minutes')),
                ('available_days', models.CharField(default='0,1,2,3,4', help_text='Available days (0=Mon, 1=Tue, 2=Wed, 3=Thu, 4=Fri, 5=Sat, 6=Sun)', max_length=20)),
                ('timezone', models.CharField(default='Africa/Johannesburg', help_text='Timezone for availability display', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_calendar_connections',
                'unique_together': {('user', 'provider')},
            },
        ),
    ]
