# Generated by Django 5.2.9 on 2025-12-04 22:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_remove_notification_application_and_more'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(help_text='Secure random token for booking URL', max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(help_text='Token expiration time (default: 7 days from creation)')),
                ('is_used', models.BooleanField(default=False, help_text='Whether the token has been used to book')),
                ('used_at', models.DateTimeField(blank=True, help_text='When the candidate completed the booking', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stage_instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking_token', to='jobs.applicationstageinstance')),
            ],
            options={
                'db_table': 'booking_tokens',
                'indexes': [models.Index(fields=['token'], name='booking_tok_token_096f18_idx'), models.Index(fields=['expires_at'], name='booking_tok_expires_c1d8ea_idx')],
            },
        ),
    ]
