# Generated by Django 5.2.9 on 2025-12-07 17:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_bookingtoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Display name (e.g., "Sales Discovery Call")', max_length=100)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=100)),
                ('category', models.CharField(choices=[('sales', 'Sales'), ('recruitment', 'Recruitment')], help_text='Category of the meeting', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Description shown on the booking page')),
                ('duration_minutes', models.PositiveIntegerField(default=30, help_text='Duration of the meeting in minutes')),
                ('buffer_before_minutes', models.PositiveIntegerField(default=0, help_text='Buffer time before the meeting')),
                ('buffer_after_minutes', models.PositiveIntegerField(default=0, help_text='Buffer time after the meeting')),
                ('location_type', models.CharField(choices=[('video', 'Video Call'), ('phone', 'Phone Call'), ('in_person', 'In Person')], default='video', help_text='Type of meeting location', max_length=20)),
                ('custom_location', models.CharField(blank=True, help_text='Custom location or phone number (for in-person/phone meetings)', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this meeting type is available for booking')),
                ('requires_approval', models.BooleanField(default=False, help_text='Whether bookings require manual approval')),
                ('max_bookings_per_day', models.PositiveIntegerField(blank=True, help_text='Maximum number of bookings per day (null = unlimited)', null=True)),
                ('confirmation_message', models.TextField(blank=True, help_text='Custom message shown after booking confirmation')),
                ('redirect_url', models.URLField(blank=True, help_text='URL to redirect to after successful booking (optional)')),
                ('color', models.CharField(default='#3B82F6', help_text='Color for calendar display (hex)', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='The recruiter/admin who owns this meeting type', on_delete=django.db.models.deletion.CASCADE, related_name='meeting_types', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meeting_types',
                'ordering': ['category', 'name'],
                'unique_together': {('owner', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attendee_name', models.CharField(help_text='Name of the attendee', max_length=255)),
                ('attendee_email', models.EmailField(help_text='Email of the attendee', max_length=254)),
                ('attendee_phone', models.CharField(blank=True, help_text='Phone number of the attendee', max_length=30)),
                ('attendee_company', models.CharField(blank=True, help_text='Company name (for sales meetings)', max_length=255)),
                ('title', models.CharField(help_text='Meeting title', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Meeting description or notes')),
                ('scheduled_at', models.DateTimeField(help_text='When the meeting is scheduled')),
                ('duration_minutes', models.PositiveIntegerField(help_text='Duration in minutes (copied from meeting type)')),
                ('timezone', models.CharField(default='Africa/Johannesburg', help_text='Timezone for the meeting', max_length=50)),
                ('location_type', models.CharField(choices=[('video', 'Video Call'), ('phone', 'Phone Call'), ('in_person', 'In Person')], default='video', max_length=20)),
                ('meeting_url', models.URLField(blank=True, help_text='Video call URL (auto-generated for Google Meet/Teams)')),
                ('location', models.CharField(blank=True, help_text='Physical location or phone number', max_length=255)),
                ('calendar_event_id', models.CharField(blank=True, help_text='ID of the calendar event (Google/Microsoft)', max_length=255)),
                ('calendar_provider', models.CharField(blank=True, choices=[('google', 'Google Calendar'), ('microsoft', 'Microsoft 365')], help_text='Which calendar provider the event was created in', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('no_show', 'No Show')], default='confirmed', max_length=20)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes (only visible to organizer)')),
                ('source', models.CharField(choices=[('public', 'Public Booking Page'), ('manual', 'Manually Created'), ('invite', 'Email Invitation')], default='public', help_text='How the booking was created', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendee_user', models.ForeignKey(blank=True, help_text='Linked user account if attendee is a registered user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attended_bookings', to=settings.AUTH_USER_MODEL)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_bookings', to=settings.AUTH_USER_MODEL)),
                ('organizer', models.ForeignKey(help_text='The recruiter/admin hosting the meeting', on_delete=django.db.models.deletion.CASCADE, related_name='organized_bookings', to=settings.AUTH_USER_MODEL)),
                ('meeting_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='scheduling.meetingtype')),
            ],
            options={
                'db_table': 'bookings',
                'ordering': ['-scheduled_at'],
                'indexes': [models.Index(fields=['organizer', 'scheduled_at'], name='bookings_organiz_05ea25_idx'), models.Index(fields=['status', 'scheduled_at'], name='bookings_status_b0ef5c_idx'), models.Index(fields=['attendee_email'], name='bookings_attende_527c6d_idx')],
            },
        ),
    ]
