# Generated by Django 5.2.9 on 2025-12-07 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0009_add_profile_suggestion'),
        ('scheduling', '0003_meetingtype_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='candidate_profile',
            field=models.ForeignKey(blank=True, help_text='Linked candidate profile if attendee is a candidate', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='candidates.candidateprofile'),
        ),
    ]
