# Generated by Django 5.2.9 on 2025-12-09 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_onboarding_stages'),
        ('scheduling', '0004_add_candidate_invitation_and_booking_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingtype',
            name='stage_change_behavior',
            field=models.CharField(choices=[('always', 'Always set to this stage'), ('only_forward', 'Only move forward (never go backwards)'), ('only_if_not_set', 'Only if no stage is currently set')], default='only_forward', help_text='How to handle stage changes', max_length=20),
        ),
        migrations.AddField(
            model_name='meetingtype',
            name='target_onboarding_stage',
            field=models.ForeignKey(blank=True, help_text='Move candidate/company to this stage when booking is created', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_types', to='core.onboardingstage'),
        ),
    ]
