# Generated by Django 5.2.9 on 2025-12-09 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_add_onboarding_stage_to_meeting_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meetingtype',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='meetingtype',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, help_text='Recruiters/admins who can use this meeting type for their booking pages', related_name='accessible_meeting_types', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meetingtype',
            name='owner',
            field=models.ForeignKey(help_text='The admin who created this meeting type', on_delete=django.db.models.deletion.CASCADE, related_name='owned_meeting_types', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meetingtype',
            name='slug',
            field=models.SlugField(help_text='URL-friendly identifier (globally unique)', max_length=100, unique=True),
        ),
    ]
