# Generated by Django 5.2.9 on 2025-12-09 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_onboarding_stages'),
        ('scheduling', '0006_add_allowed_users_to_meeting_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingtype',
            name='target_onboarding_stage_authenticated',
            field=models.ForeignKey(blank=True, help_text='Move candidate/company to this stage when booking is created by authenticated user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_types_authenticated', to='core.onboardingstage'),
        ),
        migrations.AlterField(
            model_name='meetingtype',
            name='target_onboarding_stage',
            field=models.ForeignKey(blank=True, help_text='Move candidate/company to this stage when booking is created by unauthenticated user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_types_unauthenticated', to='core.onboardingstage'),
        ),
    ]
