# Generated by Django 5.2.9 on 2025-12-18 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0008_add_show_on_dashboard_to_meeting_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='organizer',
            field=models.ForeignKey(help_text='The recruiter/admin hosting the meeting', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meetingtype',
            name='owner',
            field=models.ForeignKey(help_text='The admin who created this meeting type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_meeting_types', to=settings.AUTH_USER_MODEL),
        ),
    ]
