# Generated by Django 5.2.9 on 2025-12-24 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0009_alter_booking_organizer_alter_meetingtype_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingtype',
            name='use_for_onboarding',
            field=models.BooleanField(default=False, help_text='Use this meeting type in the onboarding wizard (sales for clients, recruitment for candidates)'),
        ),
    ]
