# Generated by Django 5.2.9 on 2025-12-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0010_add_use_for_onboarding_to_meetingtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingtype',
            name='category',
            field=models.CharField(choices=[('leads', 'Leads'), ('onboarding', 'Onboarding'), ('recruitment', 'Recruitment')], help_text='Category of the meeting', max_length=20),
        ),
    ]
