# Generated by Django 5.2.9 on 2025-12-26 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0019_add_lead_activity_model'),
        ('scheduling', '0012_migrate_meeting_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='lead',
            field=models.ForeignKey(blank=True, help_text='Linked lead if attendee is a lead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='companies.lead'),
        ),
    ]
