# Generated by Django 5.2.9 on 2025-12-26 08:33

from django.db import migrations


def backfill_booking_leads(apps, schema_editor):
    """
    Backfill existing bookings with their lead FK based on email matching.
    Only updates bookings that have a 'leads' category meeting type.
    """
    Booking = apps.get_model('scheduling', 'Booking')
    Lead = apps.get_model('companies', 'Lead')

    # Get all bookings with leads category meeting type that don't have a lead set
    leads_bookings = Booking.objects.filter(
        meeting_type__category='leads',
        lead__isnull=True
    ).select_related('meeting_type')

    for booking in leads_bookings:
        # Try to find a matching lead by email
        lead = Lead.objects.filter(email__iexact=booking.attendee_email).first()
        if lead:
            booking.lead = lead
            booking.save(update_fields=['lead'])


def reverse_backfill(apps, schema_editor):
    """Reverse migration - clear lead FK from bookings."""
    Booking = apps.get_model('scheduling', 'Booking')
    Booking.objects.filter(lead__isnull=False).update(lead=None)


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0013_add_lead_to_booking'),
        ('companies', '0019_add_lead_activity_model'),  # Ensure Lead model exists
    ]

    operations = [
        migrations.RunPython(backfill_booking_leads, reverse_backfill),
    ]
