# Generated by Django 5.2.9 on 2025-12-02 23:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0004_update_skill_categories'),
        ('companies', '0002_city_country_remove_company_interview_process_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('seniority', models.CharField(blank=True, choices=[('intern', 'Intern'), ('junior', 'Junior'), ('mid', 'Mid-Level'), ('senior', 'Senior'), ('lead', 'Lead'), ('principal', 'Principal'), ('executive', 'Executive')], max_length=20)),
                ('job_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('freelance', 'Freelance')], default='full_time', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed'), ('filled', 'Filled'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('department', models.CharField(blank=True, choices=[('engineering', 'Engineering'), ('marketing', 'Marketing'), ('sales', 'Sales'), ('operations', 'Operations'), ('design', 'Design'), ('product', 'Product'), ('hr', 'Human Resources'), ('finance', 'Finance'), ('data', 'Data & Analytics'), ('legal', 'Legal'), ('customer_success', 'Customer Success'), ('other', 'Other')], max_length=20)),
                ('summary', models.TextField(blank=True, help_text='Brief summary for job listings (2-3 sentences)')),
                ('description', models.TextField(blank=True, help_text='Full job description')),
                ('requirements', models.TextField(blank=True, help_text='Required qualifications and experience')),
                ('nice_to_haves', models.TextField(blank=True, help_text='Nice-to-have qualifications')),
                ('responsibilities', models.TextField(blank=True, help_text='Key responsibilities and duties')),
                ('work_mode', models.CharField(blank=True, choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'On-site')], max_length=20)),
                ('remote_regions', models.JSONField(blank=True, default=list, help_text='Regions where remote work is accepted')),
                ('salary_min', models.PositiveIntegerField(blank=True, null=True)),
                ('salary_max', models.PositiveIntegerField(blank=True, null=True)),
                ('salary_currency', models.CharField(choices=[('ZAR', 'South African Rand'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound')], default='ZAR', max_length=3)),
                ('salary_visible', models.BooleanField(default=True, help_text='Show salary on public job listing')),
                ('equity_offered', models.BooleanField(default=False)),
                ('benefits', models.JSONField(blank=True, default=list, help_text='Structured benefits: [{"category": "Health", "items": ["Medical aid"]}]')),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('applications_count', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('application_deadline', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_recruiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_assigned', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='companies.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_created', to=settings.AUTH_USER_MODEL)),
                ('location_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='companies.city')),
                ('location_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='companies.country')),
                ('nice_to_have_skills', models.ManyToManyField(blank=True, related_name='jobs_nice_to_have', to='candidates.skill')),
                ('required_skills', models.ManyToManyField(blank=True, related_name='jobs_required', to='candidates.skill')),
                ('technologies', models.ManyToManyField(blank=True, related_name='jobs', to='candidates.technology')),
            ],
            options={
                'db_table': 'jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
