# Generated by Django 5.2.9 on 2025-12-03 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='interview_stages',
            field=models.JSONField(blank=True, default=list, help_text='Interview stages: [{"name": "Phone Screen", "order": 1, "description": "..."}]'),
        ),
    ]
