# Generated by Django 5.2.9 on 2025-12-03 16:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_add_location_foreignkeys'),
        ('jobs', '0002_add_interview_stages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('covering_statement', models.TextField(blank=True, help_text='Cover letter or statement from the candidate')),
                ('resume_url', models.FileField(blank=True, help_text='Resume uploaded with this application (or uses profile resume)', null=True, upload_to='applications/resumes/')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('in_progress', 'In Progress'), ('offer', 'Offer Extended'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='applied', max_length=20)),
                ('current_stage_order', models.PositiveIntegerField(default=0, help_text='0=applied, 1+=corresponds to job.interview_stages[].order')),
                ('stage_notes', models.JSONField(blank=True, default=dict, help_text='Notes per stage: {"1": {"notes": "...", "updated_at": "..."}}')),
                ('source', models.CharField(choices=[('direct', 'Direct'), ('referral', 'Referral'), ('recruiter', 'Recruiter')], default='direct', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection (internal)')),
                ('feedback', models.TextField(blank=True, help_text='Internal notes about the application')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('last_status_change', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='candidates.candidateprofile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
                ('referrer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'applications',
                'ordering': ['-applied_at'],
                'unique_together': {('job', 'candidate')},
            },
        ),
    ]
