# Generated by Django 5.2.9 on 2025-12-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='final_offer_details',
            field=models.JSONField(blank=True, default=dict, help_text='Final confirmed offer details after acceptance'),
        ),
        migrations.AddField(
            model_name='application',
            name='offer_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='offer_details',
            field=models.JSONField(blank=True, default=dict, help_text='Offer details: {"salary": 50000, "currency": "ZAR", "start_date": "2024-01-15", "notes": "..."}'),
        ),
        migrations.AddField(
            model_name='application',
            name='offer_made_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='rejection_feedback',
            field=models.TextField(blank=True, help_text='Custom feedback/notes for the rejection'),
        ),
        migrations.AddField(
            model_name='application',
            name='shortlisted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='rejection_reason',
            field=models.CharField(blank=True, choices=[('internal_rejection', 'Internal Rejection'), ('client_rejection', 'Client Rejection'), ('withdrawn', 'Withdrawn'), ('invalid_shortlist', 'Invalid Shortlist'), ('candidate_not_interested', 'Candidate Not Interested')], help_text='Structured rejection reason', max_length=30),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('in_progress', 'In Progress'), ('offer_made', 'Offer Made'), ('offer_accepted', 'Offer Accepted'), ('rejected', 'Rejected')], default='applied', max_length=20),
        ),
    ]
