# Generated by Django 5.2.9 on 2025-12-04 09:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_update_application_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('stage_changed', 'Stage Changed'), ('offer_made', 'Offer Made'), ('offer_updated', 'Offer Updated'), ('offer_accepted', 'Offer Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('application_viewed', 'Application Viewed')], max_length=30)),
                ('previous_status', models.CharField(blank=True, choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('in_progress', 'In Progress'), ('offer_made', 'Offer Made'), ('offer_accepted', 'Offer Accepted'), ('rejected', 'Rejected')], max_length=20)),
                ('new_status', models.CharField(blank=True, choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('in_progress', 'In Progress'), ('offer_made', 'Offer Made'), ('offer_accepted', 'Offer Accepted'), ('rejected', 'Rejected')], max_length=20)),
                ('previous_stage', models.PositiveIntegerField(blank=True, null=True)),
                ('new_stage', models.PositiveIntegerField(blank=True, null=True)),
                ('stage_name', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context: offer_details, rejection_reason, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='jobs.application')),
                ('performed_by', models.ForeignKey(blank=True, help_text='User who performed this action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'application_activity_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='jobs.activitylog')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'application_activity_notes',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['application', '-created_at'], name='application_applica_72c016_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['activity_type'], name='application_activit_dc6a85_idx'),
        ),
    ]
