# Generated by Django 5.2.9 on 2025-12-04 11:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_add_company_invitation_token'),
        ('jobs', '0005_add_activity_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.CharField(max_length=500)),
                ('question_type', models.CharField(choices=[('text', 'Short Text'), ('textarea', 'Long Text'), ('select', 'Single Select'), ('multi_select', 'Multi Select'), ('file', 'File Upload'), ('external_link', 'External Link')], default='text', max_length=20)),
                ('options', models.JSONField(blank=True, default=list, help_text='Options for select/multi_select types: ["Option 1", "Option 2"]')),
                ('placeholder', models.CharField(blank=True, help_text='Placeholder text for text/textarea inputs', max_length=200)),
                ('helper_text', models.CharField(blank=True, help_text='Help text shown below the question', max_length=300)),
                ('is_required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='jobs.job')),
            ],
            options={
                'db_table': 'application_questions',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Template name (e.g., "Engineering Questions", "Sales Assessment")', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of when to use this template')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_templates', to='companies.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_templates_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'question_templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TemplateQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.CharField(max_length=500)),
                ('question_type', models.CharField(choices=[('text', 'Short Text'), ('textarea', 'Long Text'), ('select', 'Single Select'), ('multi_select', 'Multi Select'), ('file', 'File Upload'), ('external_link', 'External Link')], default='text', max_length=20)),
                ('options', models.JSONField(blank=True, default=list, help_text='Options for select/multi_select types: ["Option 1", "Option 2"]')),
                ('placeholder', models.CharField(blank=True, help_text='Placeholder text for text/textarea inputs', max_length=200)),
                ('helper_text', models.CharField(blank=True, help_text='Help text shown below the question', max_length=300)),
                ('is_required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='jobs.questiontemplate')),
            ],
            options={
                'db_table': 'template_questions',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer_text', models.TextField(blank=True, help_text='Text answer or JSON array for multi_select')),
                ('answer_file', models.FileField(blank=True, help_text='File upload for file type questions', null=True, upload_to='applications/answers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='jobs.application')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='jobs.applicationquestion')),
            ],
            options={
                'db_table': 'application_answers',
                'unique_together': {('application', 'question')},
            },
        ),
        migrations.CreateModel(
            name='ApplicationStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_default', models.BooleanField(default=False, help_text='Default stages that come pre-populated')),
                ('color', models.CharField(default='#6B7280', help_text='Hex color code for UI display', max_length=7)),
                ('description', models.TextField(blank=True, help_text='Description of what happens at this stage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='jobs.job')),
            ],
            options={
                'db_table': 'application_stages',
                'ordering': ['order'],
                'unique_together': {('job', 'order')},
            },
        ),
    ]
