# Generated by Django 5.2.9 on 2025-12-04 12:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_add_question_templates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewStageTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage_type', models.CharField(choices=[('application_screen', 'Application Screen'), ('phone_screening', 'Phone Screening'), ('video_call', 'Video Call Interview'), ('in_person_interview', 'In-Person Interview'), ('take_home_assessment', 'Take-Home Assessment'), ('in_person_assessment', 'In-Person Assessment'), ('custom', 'Custom')], default='custom', max_length=30)),
                ('name', models.CharField(help_text='Stage name (auto-filled from type or custom)', max_length=100)),
                ('order', models.PositiveIntegerField(help_text='Position in the interview pipeline (1-indexed)')),
                ('description', models.TextField(blank=True, help_text='Description of what happens at this stage')),
                ('default_duration_minutes', models.PositiveIntegerField(blank=True, help_text='Default interview duration in minutes', null=True)),
                ('assessment_instructions', models.TextField(blank=True, help_text='Instructions for the candidate (Markdown supported)')),
                ('assessment_instructions_file', models.FileField(blank=True, help_text='PDF or document with detailed instructions', null=True, upload_to='stage_instructions/')),
                ('assessment_external_url', models.URLField(blank=True, help_text='External assessment URL (e.g., Codility, HackerRank)')),
                ('assessment_provider_name', models.CharField(blank=True, help_text='Assessment provider name (e.g., "Codility", "HackerRank")', max_length=100)),
                ('deadline_days', models.PositiveIntegerField(blank=True, help_text='Days from assignment to deadline for assessments', null=True)),
                ('use_company_address', models.BooleanField(default=True, help_text='Use company office address by default')),
                ('custom_location', models.CharField(blank=True, help_text='Custom location if not using company address', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_interviewer', models.ForeignKey(blank=True, help_text='Default interviewer for this stage', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_interview_stages', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_templates', to='jobs.job')),
            ],
            options={
                'db_table': 'interview_stage_templates',
                'ordering': ['order'],
                'unique_together': {('job', 'order')},
            },
        ),
        migrations.CreateModel(
            name='ApplicationStageInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('awaiting_submission', 'Awaiting Submission'), ('submitted', 'Submitted'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='not_started', max_length=30)),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='Scheduled date and time for the interview', null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Actual duration (may differ from template default)', null=True)),
                ('meeting_link', models.URLField(blank=True, help_text='Video meeting link (Zoom, Teams, Google Meet, etc.)')),
                ('location', models.CharField(blank=True, help_text='Physical location for in-person interviews', max_length=500)),
                ('meeting_notes', models.TextField(blank=True, help_text='Additional meeting notes visible to candidate')),
                ('google_calendar_event_id', models.CharField(blank=True, help_text='Google Calendar event ID for syncing', max_length=255)),
                ('microsoft_calendar_event_id', models.CharField(blank=True, help_text='Microsoft 365 Calendar event ID for syncing', max_length=255)),
                ('calendar_invite_sent', models.BooleanField(default=False, help_text='Whether calendar invite was sent to participants')),
                ('deadline', models.DateTimeField(blank=True, help_text='Deadline for assessment submission', null=True)),
                ('submission_url', models.URLField(blank=True, help_text='External submission link or completed assessment URL')),
                ('submission_file', models.FileField(blank=True, help_text='Uploaded submission file', null=True, upload_to='assessment_submissions/')),
                ('submitted_at', models.DateTimeField(blank=True, help_text='When the candidate submitted their work', null=True)),
                ('recruiter_notes', models.TextField(blank=True, help_text='Internal notes for recruiters (not visible to candidate)')),
                ('feedback', models.TextField(blank=True, help_text='Interviewer feedback after the stage')),
                ('score', models.PositiveSmallIntegerField(blank=True, help_text='Score or rating (1-5 scale)', null=True)),
                ('recommendation', models.CharField(blank=True, choices=[('strong_yes', 'Strong Yes'), ('yes', 'Yes'), ('maybe', 'Maybe'), ('no', 'No'), ('strong_no', 'Strong No')], help_text='Interviewer recommendation', max_length=20)),
                ('notification_sent_at', models.DateTimeField(blank=True, help_text='When initial notification was sent', null=True)),
                ('reminder_sent_at', models.DateTimeField(blank=True, help_text='When reminder notification was sent', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the stage was marked as completed', null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_instances', to='jobs.application')),
                ('interviewer', models.ForeignKey(blank=True, help_text='Assigned interviewer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews_assigned', to=settings.AUTH_USER_MODEL)),
                ('stage_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='jobs.interviewstagetemplate')),
            ],
            options={
                'db_table': 'application_stage_instances',
                'ordering': ['stage_template__order'],
                'unique_together': {('application', 'stage_template')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('stage_scheduled', 'Interview Scheduled'), ('stage_reminder', 'Interview Reminder'), ('stage_rescheduled', 'Interview Rescheduled'), ('stage_cancelled', 'Interview Cancelled'), ('assessment_assigned', 'Assessment Assigned'), ('assessment_reminder', 'Assessment Deadline Reminder'), ('submission_received', 'Submission Received'), ('application_received', 'Application Received'), ('application_shortlisted', 'Application Shortlisted'), ('application_rejected', 'Application Rejected'), ('offer_received', 'Offer Received')], max_length=30)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('in_app', 'In-App'), ('both', 'Email & In-App')], default='both', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('action_url', models.URLField(blank=True, help_text='URL to navigate to when notification is clicked')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_error', models.TextField(blank=True, help_text='Error message if email sending failed')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='jobs.application')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('stage_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='jobs.applicationstageinstance')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['recipient', '-sent_at'], name='notificatio_recipie_d64ba4_idx'), models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_583549_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserCalendarConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('google', 'Google Calendar'), ('microsoft', 'Microsoft 365')], max_length=20)),
                ('access_token', models.TextField(help_text='OAuth access token (encrypted)')),
                ('refresh_token', models.TextField(blank=True, help_text='OAuth refresh token (encrypted)')),
                ('token_expires_at', models.DateTimeField(blank=True, help_text='When the access token expires', null=True)),
                ('provider_user_id', models.CharField(blank=True, help_text='User ID from the calendar provider', max_length=255)),
                ('provider_email', models.EmailField(blank=True, help_text='Email associated with the calendar account', max_length=254)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this connection is active')),
                ('calendar_id', models.CharField(default='primary', help_text='Which calendar to use (primary or specific calendar ID)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_calendar_connections',
                'unique_together': {('user', 'provider')},
            },
        ),
    ]
