# Generated by Django 5.2.9 on 2025-12-04 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_interview_stage_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationstageinstance',
            name='participants',
            field=models.ManyToManyField(blank=True, help_text='Additional participants (besides the primary interviewer)', related_name='interview_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='applicationstageinstance',
            name='interviewer',
            field=models.ForeignKey(blank=True, help_text='Primary interviewer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews_assigned', to=settings.AUTH_USER_MODEL),
        ),
    ]
