# Generated by Django 5.2.9 on 2025-12-04 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_add_calendar_booking_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='application',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='stage_instance',
        ),
        migrations.AlterUniqueTogether(
            name='usercalendarconnection',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usercalendarconnection',
            name='user',
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('stage_changed', 'Stage Changed'), ('offer_made', 'Offer Made'), ('offer_updated', 'Offer Updated'), ('offer_accepted', 'Offer Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('application_viewed', 'Application Viewed'), ('booking_link_sent', 'Booking Link Sent'), ('interview_booked', 'Interview Booked'), ('interview_scheduled', 'Interview Scheduled'), ('interview_rescheduled', 'Interview Rescheduled'), ('interview_cancelled', 'Interview Cancelled')], max_length=30),
        ),
        migrations.DeleteModel(
            name='BookingToken',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='UserCalendarConnection',
        ),
    ]
