# Generated by Django 5.2.9 on 2025-12-05 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_remove_notification_application_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='assigned_client',
            field=models.ForeignKey(blank=True, help_text='Client user assigned to this job for notifications', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_as_client', to=settings.AUTH_USER_MODEL),
        ),
    ]
