# Generated by Django 5.2.9 on 2025-12-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_job_assigned_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='new_status',
            field=models.CharField(blank=True, choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('in_progress', 'In Progress'), ('offer_made', 'Offer Made'), ('offer_accepted', 'Offer Accepted'), ('offer_declined', 'Offer Declined'), ('rejected', 'Rejected')], max_length=20),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('in_progress', 'In Progress'), ('offer_made', 'Offer Made'), ('offer_accepted', 'Offer Accepted'), ('offer_declined', 'Offer Declined'), ('rejected', 'Rejected')], max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('in_progress', 'In Progress'), ('offer_made', 'Offer Made'), ('offer_accepted', 'Offer Accepted'), ('offer_declined', 'Offer Declined'), ('rejected', 'Rejected')], default='applied', max_length=20),
        ),
    ]
