# Generated by Django 5.2.9 on 2025-12-07 23:14

import django.db.models.deletion
from django.db import migrations, models


def migrate_current_stage_order_to_fk(apps, schema_editor):
    """Migrate current_stage_order integer to current_stage FK."""
    Application = apps.get_model('jobs', 'Application')
    InterviewStageTemplate = apps.get_model('jobs', 'InterviewStageTemplate')

    for application in Application.objects.filter(current_stage_order__gt=0):
        # Find the template for this job with matching order
        template = InterviewStageTemplate.objects.filter(
            job=application.job,
            order=application.current_stage_order
        ).first()
        if template:
            application.current_stage = template
            application.save(update_fields=['current_stage'])


def reverse_migrate(apps, schema_editor):
    """Reverse migration - set current_stage_order from FK."""
    Application = apps.get_model('jobs', 'Application')

    for application in Application.objects.exclude(current_stage__isnull=True):
        application.current_stage_order = application.current_stage.order
        application.save(update_fields=['current_stage_order'])


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_add_offer_declined_status'),
    ]

    operations = [
        # Step 1: Add the new FK field (keep old field for data migration)
        migrations.AddField(
            model_name='application',
            name='current_stage',
            field=models.ForeignKey(
                blank=True,
                help_text='Current interview stage (null = Applied/not yet in pipeline)',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='applications_at_stage',
                to='jobs.interviewstagetemplate'
            ),
        ),
        # Step 2: Migrate data from old field to new FK
        migrations.RunPython(migrate_current_stage_order_to_fk, reverse_migrate),
        # Step 3: Remove old field
        migrations.RemoveField(
            model_name='application',
            name='current_stage_order',
        ),
    ]
