# Generated by Django 5.2.9 on 2025-12-08 09:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_add_current_stage_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='assigned_recruiter',
        ),
        migrations.AddField(
            model_name='job',
            name='assigned_recruiters',
            field=models.ManyToManyField(blank=True, help_text='Recruiters and admins assigned to manage this job', related_name='jobs_assigned', to=settings.AUTH_USER_MODEL),
        ),
    ]
