# Generated by Django 5.2.9 on 2025-12-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_change_assigned_recruiter_to_many_to_many'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='positions_to_fill',
            field=models.PositiveIntegerField(default=1, help_text='Number of positions to fill for this job'),
        ),
    ]
