# Generated by Django 5.2.9 on 2025-12-09 12:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_add_positions_to_fill'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='assigned_recruiters',
            field=models.ManyToManyField(blank=True, help_text='Recruiters/admins assigned to manage this application', related_name='assigned_applications', to=settings.AUTH_USER_MODEL),
        ),
    ]
