# Generated by Django 5.2.9 on 2025-12-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_add_assigned_recruiters_to_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='applied_feedback',
            field=models.TextField(blank=True, help_text='Recruiter feedback/notes for the Applied stage'),
        ),
        migrations.AddField(
            model_name='application',
            name='applied_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Score given at the Applied stage (1-10)', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='shortlisted_feedback',
            field=models.TextField(blank=True, help_text='Recruiter feedback/notes for the Shortlisted stage'),
        ),
        migrations.AddField(
            model_name='application',
            name='shortlisted_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Score given at the Shortlisted stage (1-10)', null=True),
        ),
    ]
