# Generated by Django 5.2.9 on 2025-12-10 15:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_add_application_status_feedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StageFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage_type', models.CharField(blank=True, choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview Stage')], help_text='Type of status stage (for Applied/Shortlisted feedback)', max_length=20, null=True)),
                ('comment', models.TextField(help_text='The feedback comment text')),
                ('score', models.PositiveSmallIntegerField(blank=True, help_text='Optional score (1-10)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_feedbacks', to='jobs.application')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_feedbacks', to=settings.AUTH_USER_MODEL)),
                ('stage_instance', models.ForeignKey(blank=True, help_text='Interview stage instance (for interview stage feedback)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='jobs.applicationstageinstance')),
            ],
            options={
                'db_table': 'stage_feedbacks',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['application', 'stage_type'], name='stage_feedb_applica_fb3f7b_idx'), models.Index(fields=['stage_instance'], name='stage_feedb_stage_i_eb449c_idx'), models.Index(fields=['created_at'], name='stage_feedb_created_4efc60_idx')],
            },
        ),
    ]
