# Generated by Django 5.2.9 on 2025-12-11 06:47

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_add_can_view_all_candidates'),
        ('jobs', '0019_add_stage_feedback_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortlistQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.CharField(help_text='The screening question text', max_length=500)),
                ('description', models.TextField(blank=True, help_text='Guidance for reviewers on how to evaluate this question')),
                ('is_required', models.BooleanField(default=False, help_text='Whether reviewers must answer this question')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlist_questions', to='jobs.job')),
            ],
            options={
                'db_table': 'shortlist_questions',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShortlistQuestionTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Template name (e.g., "Technical Screening", "Culture Fit")', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of when to use this template')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlist_question_templates', to='companies.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shortlist_templates_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shortlist_question_templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShortlistTemplateQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.CharField(help_text='The screening question text', max_length=500)),
                ('description', models.TextField(blank=True, help_text='Guidance for reviewers on how to evaluate this question')),
                ('is_required', models.BooleanField(default=False, help_text='Whether reviewers must answer this question')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='jobs.shortlistquestiontemplate')),
            ],
            options={
                'db_table': 'shortlist_template_questions',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShortlistAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.PositiveSmallIntegerField(help_text='Score from 1-5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('notes', models.TextField(blank=True, help_text='Optional notes explaining the score')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlist_answers', to='jobs.application')),
                ('reviewer', models.ForeignKey(help_text='The user who provided this score', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shortlist_reviews', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='jobs.shortlistquestion')),
            ],
            options={
                'db_table': 'shortlist_answers',
                'indexes': [models.Index(fields=['application', 'reviewer'], name='shortlist_a_applica_161bcd_idx'), models.Index(fields=['question'], name='shortlist_a_questio_2aa459_idx')],
                'unique_together': {('application', 'question', 'reviewer')},
            },
        ),
    ]
