# Generated by Django 5.2.9 on 2025-12-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0020_add_shortlist_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='seniority',
            field=models.CharField(blank=True, choices=[('intern', 'Intern'), ('junior', 'Junior'), ('mid', 'Mid-Level'), ('senior', 'Senior'), ('lead', 'Lead'), ('principal', 'Principal'), ('executive', 'Executive / C-Suite')], max_length=20),
        ),
    ]
