# Generated by Django 5.2.9 on 2025-12-22 10:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0022_remove_orphaned_is_csuite_column'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_replacement',
            field=models.BooleanField(default=False, help_text='True if this application filled a replacement position'),
        ),
        migrations.AddField(
            model_name='application',
            name='replaced_application',
            field=models.ForeignKey(blank=True, help_text='The original application/placement this is replacing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_applications', to='jobs.application'),
        ),
        migrations.CreateModel(
            name='ReplacementRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason_category', models.CharField(choices=[('resignation', 'Candidate Resigned'), ('termination', 'Candidate Terminated'), ('performance', 'Performance Issues'), ('cultural_fit', 'Cultural Fit Issues'), ('no_show', 'Candidate Did Not Start'), ('other', 'Other')], help_text='Category of reason for the replacement request', max_length=20)),
                ('reason_details', models.TextField(blank=True, help_text='Detailed explanation of why replacement is needed')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved_free', 'Approved (Free)'), ('approved_discounted', 'Approved (Discounted)'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('discount_percentage', models.PositiveIntegerField(blank=True, help_text='Discount percentage if approved as discounted (e.g., 50 = 50% off placement fee)', null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True, help_text='When the request was submitted')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the request was reviewed', null=True)),
                ('review_notes', models.TextField(blank=True, help_text='Notes from the reviewer explaining the decision')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(help_text='The original placement/hire being replaced', on_delete=django.db.models.deletion.CASCADE, related_name='replacement_request', to='jobs.application')),
                ('requested_by', models.ForeignKey(help_text='Client user who submitted the request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_requests_made', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who reviewed the request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_requests_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Replacement Request',
                'verbose_name_plural': 'Replacement Requests',
                'db_table': 'replacement_requests',
                'ordering': ['-requested_at'],
            },
        ),
    ]
