# Generated by Django 5.2.9 on 2025-12-02 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_update_skill_categories'),
        ('companies', '0001_initial'),
    ]

    operations = [
        # Create new models first
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'db_table': 'countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='companies.country')),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'db_table': 'cities',
                'ordering': ['name'],
                'unique_together': {('name', 'country')},
            },
        ),
        # Remove old fields
        migrations.RemoveField(
            model_name='company',
            name='interview_process',
        ),
        migrations.RemoveField(
            model_name='company',
            name='tech_stack',
        ),
        migrations.RemoveField(
            model_name='company',
            name='headquarters_city',
        ),
        migrations.RemoveField(
            model_name='company',
            name='headquarters_country',
        ),
        # Add new fields
        migrations.AddField(
            model_name='company',
            name='technologies',
            field=models.ManyToManyField(blank=True, related_name='companies', to='candidates.technology'),
        ),
        migrations.AlterField(
            model_name='company',
            name='remote_work_policy',
            field=models.CharField(blank=True, choices=[('fully_remote', 'Fully Remote'), ('remote_first', 'Remote First'), ('hybrid', 'Hybrid'), ('office_first', 'Office First'), ('office_only', 'Office Only')], max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='headquarters_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headquartered_companies', to='companies.city'),
        ),
        migrations.AddField(
            model_name='company',
            name='headquarters_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headquartered_companies', to='companies.country'),
        ),
    ]
