# Generated by Django 5.2.9 on 2025-12-03 09:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_add_company_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinvitation',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
