# Generated by Django 5.2.9 on 2025-12-08 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_change_assigned_to_to_m2m'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='onboarding_stage',
            field=models.ForeignKey(blank=True, limit_choices_to={'entity_type': 'company'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='core.onboardingstage'),
        ),
    ]
