# Generated by Django 5.2.9 on 2025-12-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_company_onboarding_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='can_view_all_candidates',
            field=models.BooleanField(default=False, help_text='If enabled, users from this company can view all candidates. Otherwise, they only see applicants to their jobs.'),
        ),
    ]
