# Generated by Django 5.2.9 on 2025-12-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_add_can_view_all_candidates'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_platform',
            field=models.BooleanField(default=False, help_text='If true, this is the platform company. Staff (admin/recruiter) users are automatically added as members.'),
        ),
    ]
