# Generated by Django 5.2.9 on 2025-12-18 06:29

from django.db import migrations


def fix_platform_company_staff_roles(apps, schema_editor):
    """
    Fix existing CompanyUser roles for the platform company.

    System role mapping:
    - Admin → Company Admin
    - Recruiter → Company Viewer
    """
    Company = apps.get_model('companies', 'Company')
    CompanyUser = apps.get_model('companies', 'CompanyUser')
    User = apps.get_model('users', 'User')

    # Find the platform company
    platform_company = Company.objects.filter(is_platform=True).first()
    if not platform_company:
        return

    # Get all CompanyUsers for the platform company
    platform_memberships = CompanyUser.objects.filter(company=platform_company)

    for membership in platform_memberships:
        user = membership.user
        # Map system role to company role
        if user.role == 'admin':
            new_role = 'admin'
        elif user.role == 'recruiter':
            new_role = 'viewer'
        else:
            continue  # Skip non-staff users

        # Update if role is different
        if membership.role != new_role:
            membership.role = new_role
            membership.save(update_fields=['role'])


def reverse_migration(apps, schema_editor):
    """
    Reverse: Set all platform company staff back to admin role.
    """
    Company = apps.get_model('companies', 'Company')
    CompanyUser = apps.get_model('companies', 'CompanyUser')

    platform_company = Company.objects.filter(is_platform=True).first()
    if not platform_company:
        return

    # Set all platform company members back to admin
    CompanyUser.objects.filter(company=platform_company).update(role='admin')


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_add_is_platform_flag'),
    ]

    operations = [
        migrations.RunPython(fix_platform_company_staff_roles, reverse_migration),
    ]
