# Generated by Django 5.2.9 on 2025-12-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_fix_platform_company_staff_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='service_type',
            field=models.CharField(blank=True, choices=[('headhunting', 'Headhunting'), ('retained', 'Retained')], help_text='The recruitment service package for this company (Headhunting or Retained)', max_length=20, null=True),
        ),
    ]
