# Generated by Django 5.2.9 on 2025-12-20 20:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_add_service_type'),
        ('subscriptions', '0005_add_service_type_to_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsAcceptance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_slug', models.CharField(max_length=255)),
                ('document_title', models.CharField(blank=True, max_length=255)),
                ('document_version', models.CharField(blank=True, max_length=50)),
                ('context', models.CharField(choices=[('company_creation', 'Company Creation'), ('service_type_change', 'Service Type Change'), ('contract_renewal', 'Contract Renewal')], default='company_creation', max_length=30)),
                ('service_type', models.CharField(blank=True, choices=[('headhunting', 'Headhunting'), ('retained', 'Retained')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terms_acceptances', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms_acceptances', to='companies.company')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terms_acceptances', to='subscriptions.subscription')),
            ],
            options={
                'db_table': 'terms_acceptances',
                'ordering': ['-accepted_at'],
            },
        ),
    ]
