# Generated by Django 5.2.9 on 2025-12-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0013_add_terms_acceptance'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='onboarding_completed_at',
            field=models.DateTimeField(blank=True, help_text='When the client completed their onboarding wizard', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='onboarding_steps_completed',
            field=models.JSONField(blank=True, default=dict, help_text='Tracks completion of onboarding steps: {"profile": true, "billing": true, ...}'),
        ),
    ]
