# Generated by Django 5.2.9 on 2025-12-24 12:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0012_candidateprofile_onboarding_stage'),
        ('companies', '0014_client_onboarding'),
        ('core', '0006_fix_onboarding_stages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Contact name', max_length=255)),
                ('email', models.EmailField(help_text='Contact email', max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('company_name', models.CharField(help_text='Company they work at', max_length=255)),
                ('company_website', models.URLField(blank=True)),
                ('company_size', models.CharField(blank=True, choices=[('1-10', '1-10 employees'), ('11-50', '11-50 employees'), ('51-200', '51-200 employees'), ('201-500', '201-500 employees'), ('501-1000', '501-1000 employees'), ('1000+', '1000+ employees')], max_length=20)),
                ('source', models.CharField(choices=[('referral', 'Referral'), ('website', 'Website'), ('linkedin', 'LinkedIn'), ('cold_outreach', 'Cold Outreach'), ('event', 'Event/Conference'), ('inbound', 'Inbound Inquiry'), ('other', 'Other')], default='other', max_length=20)),
                ('source_detail', models.CharField(blank=True, help_text='Additional source details (e.g., referrer name, event name)', max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Recruiter/admin managing this lead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('converted_to_company', models.ForeignKey(blank=True, help_text='Company created when lead converted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_lead', to='companies.company')),
                ('converted_to_user', models.ForeignKey(blank=True, help_text='User created when lead signed up', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_lead', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_created', to=settings.AUTH_USER_MODEL)),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='candidates.industry')),
                ('onboarding_stage', models.ForeignKey(blank=True, limit_choices_to={'entity_type': 'company'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='core.onboardingstage')),
            ],
            options={
                'db_table': 'leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
