# Generated by Django 5.2.9 on 2025-12-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0015_add_lead_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='is_replied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='source_page',
            field=models.CharField(blank=True, help_text='Page URL where inbound lead submitted contact form', max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='subject',
            field=models.CharField(blank=True, help_text='Subject/reason for contact (for inbound leads)', max_length=200),
        ),
    ]
