# Generated by Django 5.2.9 on 2025-12-24 13:08

from django.db import migrations


def migrate_contact_submissions_to_leads(apps, schema_editor):
    """
    Migrate existing ContactSubmission records to Lead records.
    Contact submissions become inbound leads.
    """
    ContactSubmission = apps.get_model('cms', 'ContactSubmission')
    Lead = apps.get_model('companies', 'Lead')

    for submission in ContactSubmission.objects.all():
        Lead.objects.create(
            id=submission.id,  # Preserve the UUID
            name=submission.name,
            email=submission.email,
            phone=submission.phone or '',
            company_name=submission.company or 'Not provided',
            subject=submission.subject or '',
            notes=submission.message,  # Message goes to notes
            source='inbound',
            source_page=submission.source_page or '',
            is_read=submission.is_read,
            is_replied=submission.is_replied,
            created_at=submission.created_at,
            updated_at=submission.updated_at,
        )


def reverse_migration(apps, schema_editor):
    """
    Remove migrated leads (those with source='inbound').
    Note: This doesn't restore the original ContactSubmission records.
    """
    Lead = apps.get_model('companies', 'Lead')
    Lead.objects.filter(source='inbound').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0016_add_lead_contact_fields'),
        ('cms', '0001_initial'),  # Ensure CMS models are available
    ]

    operations = [
        migrations.RunPython(
            migrate_contact_submissions_to_leads,
            reverse_migration,
        ),
    ]
