# Generated by Django 5.2.9 on 2025-12-24 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def forward_migrate_assignments(apps, schema_editor):
    """Store FK assignments in temp storage before removing the field."""
    Lead = apps.get_model('companies', 'Lead')
    # Store assignments in memory for later use
    assignments = {}
    for lead in Lead.objects.exclude(assigned_to__isnull=True):
        assignments[str(lead.id)] = lead.assigned_to_id

    # Store in a temporary file for the next step
    import json
    import os
    temp_file = os.path.join(os.path.dirname(__file__), '_temp_lead_assignments.json')
    with open(temp_file, 'w') as f:
        json.dump(assignments, f)


def restore_assignments(apps, schema_editor):
    """Restore FK assignments to M2M field."""
    import json
    import os
    temp_file = os.path.join(os.path.dirname(__file__), '_temp_lead_assignments.json')

    if not os.path.exists(temp_file):
        return

    Lead = apps.get_model('companies', 'Lead')

    with open(temp_file, 'r') as f:
        assignments = json.load(f)

    for lead_id, user_id in assignments.items():
        try:
            lead = Lead.objects.get(id=lead_id)
            lead.assigned_to.add(user_id)
        except Lead.DoesNotExist:
            pass

    # Clean up temp file
    os.remove(temp_file)


def noop(apps, schema_editor):
    """No-op reverse for the data migration."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0017_migrate_contact_submissions_to_leads'),
        ('core', '0007_lead_assigned_to_many_to_many'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 1. Store existing FK assignments before removing field
        migrations.RunPython(forward_migrate_assignments, noop),

        # 2. Remove the old ForeignKey field
        migrations.RemoveField(
            model_name='lead',
            name='assigned_to',
        ),

        # 3. Update onboarding_stage limit_choices_to (already had entity_type='lead')
        migrations.AlterField(
            model_name='lead',
            name='onboarding_stage',
            field=models.ForeignKey(blank=True, limit_choices_to={'entity_type': 'lead'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='core.onboardingstage'),
        ),

        # 4. Add the new ManyToMany field
        migrations.AddField(
            model_name='lead',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, help_text='Recruiters/admins managing this lead', related_name='assigned_leads', to=settings.AUTH_USER_MODEL),
        ),

        # 5. Restore assignments from stored data
        migrations.RunPython(restore_assignments, noop),
    ]
