# Generated by Django 5.2.9 on 2025-12-25 16:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0018_lead_assigned_to_many_to_many'),
        ('core', '0007_lead_assigned_to_many_to_many'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('note_added', 'Note Added'), ('stage_changed', 'Stage Changed'), ('meeting_scheduled', 'Meeting Scheduled'), ('meeting_completed', 'Meeting Completed'), ('meeting_cancelled', 'Meeting Cancelled'), ('email_sent', 'Email Sent'), ('call_logged', 'Call Logged'), ('invitation_sent', 'Invitation Sent'), ('converted', 'Converted to Client'), ('assigned', 'Assigned'), ('created', 'Lead Created')], max_length=30)),
                ('content', models.TextField(blank=True, help_text='Note content or activity description')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context: meeting_id, email_subject, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='companies.lead')),
                ('new_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.onboardingstage')),
                ('performed_by', models.ForeignKey(blank=True, help_text='User who performed this action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_activities', to=settings.AUTH_USER_MODEL)),
                ('previous_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.onboardingstage')),
            ],
            options={
                'verbose_name_plural': 'Lead activities',
                'db_table': 'lead_activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['lead', '-created_at'], name='lead_activi_lead_id_d58c46_idx'), models.Index(fields=['activity_type'], name='lead_activi_activit_c10782_idx')],
            },
        ),
    ]
