# Generated by Django 5.2.9 on 2026-01-04 06:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0019_add_lead_activity_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('note_added', 'Note Added'), ('call_logged', 'Call Logged'), ('email_sent', 'Email Sent'), ('meeting_scheduled', 'Meeting Scheduled'), ('meeting_completed', 'Meeting Completed'), ('meeting_cancelled', 'Meeting Cancelled'), ('assigned', 'Assigned'), ('status_changed', 'Status Changed')], max_length=30)),
                ('content', models.TextField(blank=True, help_text='Note content or activity description')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional activity-specific data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='companies.company')),
                ('performed_by', models.ForeignKey(blank=True, help_text='User who performed this action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Company activities',
                'db_table': 'company_activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
