# Generated by Django 5.2.9 on 2025-12-07 16:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0009_add_profile_suggestion'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruiterProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('professional_title', models.CharField(blank=True, help_text='e.g., Senior Technical Recruiter', max_length=100)),
                ('bio', models.TextField(blank=True, help_text='About/bio text for the recruiter profile')),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL')),
                ('years_of_experience', models.PositiveSmallIntegerField(blank=True, help_text='Years of recruiting experience', null=True)),
                ('location', models.CharField(blank=True, help_text='City, Country or general location', max_length=100)),
                ('timezone', models.CharField(default='Africa/Johannesburg', help_text='Preferred timezone for scheduling', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('industries', models.ManyToManyField(blank=True, help_text='Industries the recruiter specializes in', related_name='recruiters', to='candidates.industry')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recruiter Profile',
                'verbose_name_plural': 'Recruiter Profiles',
                'db_table': 'recruiter_profiles',
            },
        ),
    ]
