# Generated by Django 5.2.9 on 2025-12-07 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_add_company_invitation_token'),
        ('users', '0002_add_recruiter_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='location',
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='city',
            field=models.ForeignKey(blank=True, help_text='City where the recruiter is based', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruiters', to='companies.city'),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='country',
            field=models.ForeignKey(blank=True, help_text='Country where the recruiter is based', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruiters', to='companies.country'),
        ),
    ]
