# Generated by Django 5.2.9 on 2025-12-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_recruiterprofile_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofile',
            name='booking_slug',
            field=models.SlugField(blank=True, help_text='URL slug for public booking page (auto-generated from name)', max_length=100, unique=True),
        ),
    ]
