# Generated by Django 5.2.9 on 2025-12-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_booking_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_pending_signup',
            field=models.BooleanField(default=False, help_text='True if user was auto-created from booking and has not completed signup'),
        ),
    ]
