# Generated by Django 5.2.9 on 2025-12-08 19:06

from django.db import migrations
from django.utils.text import slugify


def seed_onboarding_stages(apps, schema_editor):
    """Seed initial onboarding stages for companies and candidates."""
    OnboardingStage = apps.get_model('core', 'OnboardingStage')

    # Company stages
    company_stages = [
        ('Meeting Booked', '#3B82F6', False),      # Blue
        ("T&C's Sent", '#8B5CF6', False),          # Purple
        ("T&C's Signed", '#6366F1', False),        # Indigo
        ('Profile Completed', '#10B981', False),    # Emerald
        ('Billing Completed', '#14B8A6', False),    # Teal
        ('Team Added', '#06B6D4', False),           # Cyan
        ('Onboarded', '#22C55E', True),             # Green (terminal)
        ('Not Onboarded', '#EF4444', True),         # Red (terminal)
    ]

    # Candidate stages
    candidate_stages = [
        ('Meeting Booked', '#3B82F6', False),      # Blue
        ('Profile Review', '#8B5CF6', False),      # Purple
        ('Onboarded', '#22C55E', True),            # Green (terminal)
        ('Not Onboarded', '#EF4444', True),        # Red (terminal)
    ]

    # Create company stages
    for i, (name, color, is_terminal) in enumerate(company_stages):
        OnboardingStage.objects.create(
            name=name,
            slug=slugify(name),
            entity_type='company',
            order=i,
            color=color,
            is_terminal=is_terminal,
            is_active=True,
        )

    # Create candidate stages
    for i, (name, color, is_terminal) in enumerate(candidate_stages):
        OnboardingStage.objects.create(
            name=name,
            slug=slugify(name),
            entity_type='candidate',
            order=i,
            color=color,
            is_terminal=is_terminal,
            is_active=True,
        )


def reverse_seed(apps, schema_editor):
    """Remove seeded onboarding stages."""
    OnboardingStage = apps.get_model('core', 'OnboardingStage')
    OnboardingStage.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_onboarding_stages, reverse_seed),
    ]
