# Generated by Django 5.2.9 on 2025-12-08 19:06

from django.db import migrations
from django.utils.text import slugify


def seed_onboarding_stages(apps, schema_editor):
    """Seed initial onboarding stages for companies and candidates."""
    OnboardingStage = apps.get_model('core', 'OnboardingStage')

    # Company stages - Full pipeline from prospecting to onboarded
    # Prospecting stages (admin-driven)
    # Onboarding stages (client-driven via wizard)
    # Post-wizard stages (admin-driven)
    company_stages = [
        # Prospecting
        ('Lead', 'lead', '#9CA3AF', False),                           # Gray
        ('Qualified', 'qualified', '#F59E0B', False),                 # Amber
        ('Sales Meeting Booked', 'sales-meeting-booked', '#3B82F6', False),  # Blue
        ('Invitation Sent', 'invitation-sent', '#8B5CF6', False),     # Purple
        # Onboarding wizard steps
        ('Onboarding: Contract', 'onboarding-contract', '#6366F1', False),   # Indigo
        ('Onboarding: Profile', 'onboarding-profile', '#10B981', False),     # Emerald
        ('Onboarding: Billing', 'onboarding-billing', '#14B8A6', False),     # Teal
        ('Onboarding: Team', 'onboarding-team', '#06B6D4', False),           # Cyan
        ('Onboarding: Call Booked', 'onboarding-call-booked', '#0EA5E9', False),  # Sky
        # Post-wizard
        ('Onboarding Call', 'onboarding-call', '#A855F7', False),     # Purple
        ('Onboarded', 'onboarded', '#22C55E', True),                  # Green (terminal)
        ('Not Onboarded', 'not-onboarded', '#EF4444', True),          # Red (terminal)
    ]

    # Candidate stages
    candidate_stages = [
        ('Lead', 'lead', '#9CA3AF', False),                    # Gray
        ('Meeting Booked', 'meeting-booked', '#3B82F6', False),  # Blue
        ('Profile Review', 'profile-review', '#8B5CF6', False),  # Purple
        ('Onboarded', 'onboarded', '#22C55E', True),             # Green (terminal)
        ('Not Onboarded', 'not-onboarded', '#EF4444', True),     # Red (terminal)
    ]

    # Create company stages
    for i, (name, slug, color, is_terminal) in enumerate(company_stages):
        OnboardingStage.objects.create(
            name=name,
            slug=slug,
            entity_type='company',
            order=i,
            color=color,
            is_terminal=is_terminal,
            is_active=True,
        )

    # Create candidate stages
    for i, (name, slug, color, is_terminal) in enumerate(candidate_stages):
        OnboardingStage.objects.create(
            name=name,
            slug=slug,
            entity_type='candidate',
            order=i,
            color=color,
            is_terminal=is_terminal,
            is_active=True,
        )


def reverse_seed(apps, schema_editor):
    """Remove seeded onboarding stages."""
    OnboardingStage = apps.get_model('core', 'OnboardingStage')
    OnboardingStage.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_onboarding_stages, reverse_seed),
    ]
