# Generated by Django 5.2.9 on 2025-12-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_dashboard_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardsettings',
            name='clients_can_view_all_candidates',
            field=models.BooleanField(default=False, help_text='If enabled, clients can view all candidates. If disabled, clients only see candidates who applied to their jobs.'),
        ),
    ]
