# Generated by Django 5.2.9 on 2025-12-10 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_clients_can_view_all_candidates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboardsettings',
            name='clients_can_view_all_candidates',
        ),
    ]
