# Generated by Django 5.2.9 on 2025-12-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_fix_onboarding_stages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardinghistory',
            name='entity_type',
            field=models.CharField(choices=[('lead', 'Lead'), ('company', 'Company'), ('candidate', 'Candidate')], max_length=20),
        ),
        migrations.AlterField(
            model_name='onboardingstage',
            name='entity_type',
            field=models.CharField(choices=[('lead', 'Lead'), ('company', 'Company'), ('candidate', 'Candidate')], max_length=20),
        ),
    ]
