# Generated by Django 5.2.9 on 2025-12-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_lead_assigned_to_many_to_many'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardinghistory',
            name='entity_id',
            field=models.CharField(max_length=36),
        ),
    ]
