# Generated by Django 5.2.9 on 2025-12-30 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_task_model'),
        ('jobs', '0023_add_replacement_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='stage_template',
            field=models.ForeignKey(blank=True, help_text='Optional: specific interview stage this task relates to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='jobs.interviewstagetemplate'),
        ),
        migrations.AlterField(
            model_name='task',
            name='entity_type',
            field=models.CharField(choices=[('lead', 'Lead'), ('company', 'Company'), ('candidate', 'Candidate'), ('application', 'Application')], max_length=20),
        ),
    ]
