# Generated by Django 5.2.9 on 2025-12-31 22:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_application_entity_type_and_stage_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_notes', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.task')),
            ],
            options={
                'db_table': 'task_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('created', 'Task Created'), ('status_changed', 'Status Changed'), ('priority_changed', 'Priority Changed'), ('assigned', 'Assigned'), ('reassigned', 'Reassigned'), ('due_date_changed', 'Due Date Changed'), ('completed', 'Completed'), ('reopened', 'Reopened'), ('note_added', 'Note Added'), ('updated', 'Updated')], max_length=30)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_activities', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.task')),
            ],
            options={
                'db_table': 'task_activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['task', '-created_at'], name='task_activi_task_id_e45ba7_idx'), models.Index(fields=['activity_type', '-created_at'], name='task_activi_activit_86c948_idx'), models.Index(fields=['performed_by', '-created_at'], name='task_activi_perform_a299ea_idx')],
            },
        ),
    ]
