# Generated by Django 5.2.9 on 2025-12-17 17:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0009_add_can_view_all_candidates'),
        ('jobs', '0020_add_shortlist_questions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('post_type', models.CharField(choices=[('article', 'Article'), ('update', 'Quick Update'), ('job_announcement', 'Job Announcement')], default='update', max_length=20)),
                ('title', models.CharField(blank=True, help_text='Required for articles, optional for updates', max_length=200)),
                ('content', models.TextField(blank=True, help_text='Plain text for updates (max ~500 chars recommended)')),
                ('content_blocks', models.JSONField(blank=True, help_text='Editor.js JSON blocks for articles', null=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='feed/')),
                ('featured_image_alt', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_posts', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_posts', to='companies.company')),
                ('job', models.ForeignKey(blank=True, help_text='Linked job for job_announcement posts', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feed_posts', to='jobs.job')),
            ],
            options={
                'db_table': 'feed_posts',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['-published_at', '-created_at'], name='feed_posts_publish_198f8d_idx'), models.Index(fields=['company', '-published_at'], name='feed_posts_company_1be507_idx'), models.Index(fields=['post_type', '-published_at'], name='feed_posts_post_ty_081611_idx'), models.Index(fields=['status'], name='feed_posts_status_741a78_idx')],
            },
        ),
    ]
