# Generated by Django 5.2.9 on 2025-12-17 17:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('feed', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField()),
                ('content', models.TextField(help_text='Comment text (max 1000 chars recommended)')),
                ('is_active', models.BooleanField(default=True, help_text='Soft delete flag - inactive comments are hidden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_comments', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='contenttypes.contenttype')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent comment for threaded replies', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='feed.comment')),
            ],
            options={
                'db_table': 'feed_comments',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='feed_commen_content_ad8602_idx'), models.Index(fields=['author', '-created_at'], name='feed_commen_author__83a627_idx'), models.Index(fields=['parent'], name='feed_commen_parent__576c78_idx'), models.Index(fields=['is_active'], name='feed_commen_is_acti_8ac452_idx')],
            },
        ),
    ]
